// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type OptionsLegacyParser } from '@hey-api/client-fetch';
import type { GetSiteData, GetSiteError, GetSiteResponse, GetEventsData, GetEventsError, GetEventsResponse, GetEventDatesData, GetEventDatesError, GetEventDatesResponse, GetEventData, GetEventError, GetEventResponse, GetPagesData, GetPagesError, GetPagesResponse, GetPageData, GetPageError, GetPageResponse, GetProfilesData, GetProfilesError, GetProfilesResponse, GetProfileData, GetProfileError, GetProfileResponse, GetProfileEventsData, GetProfileEventsError, GetProfileEventsResponse, GetProductsData, GetProductsError, GetProductsResponse, GetProductData, GetProductError, GetProductResponse, SearchSiteData, SearchSiteError, SearchSiteResponse, GetTagsData, GetTagsError, GetTagsResponse, ListSiteDomainsData, ListSiteDomainsError, ListSiteDomainsResponse, GetSiteByDomainData, GetSiteByDomainError, GetSiteByDomainResponse, GetEmailConfigData, GetEmailConfigError, GetEmailConfigResponse, UpdateEmailConfigData, UpdateEmailConfigError, UpdateEmailConfigResponse, GetDomainStatusData, GetDomainStatusError, GetDomainStatusResponse, AddCustomDomainData, AddCustomDomainError, AddCustomDomainResponse, RemoveCustomDomainData, RemoveCustomDomainError, RemoveCustomDomainResponse, VerifyDomainData, VerifyDomainError, VerifyDomainResponse, GetEmailsData, GetEmailsError, GetEmailsResponse, GetEmailStatsData, GetEmailStatsError, GetEmailStatsResponse, GetEmailByIdData, GetEmailByIdError, GetEmailByIdResponse, GetEmailBatchesData, GetEmailBatchesError, GetEmailBatchesResponse, CreateDraftBatchData, CreateDraftBatchError, CreateDraftBatchResponse, GetEmailBatchData, GetEmailBatchError, GetEmailBatchResponse, UpdateDraftBatchData, UpdateDraftBatchError, UpdateDraftBatchResponse, DeleteBatchData, DeleteBatchError, DeleteBatchResponse, CreateAndSendBatchData, CreateAndSendBatchError, CreateAndSendBatchResponse, SendBatchData, SendBatchError, SendBatchResponse } from './types.gen';

export const client = createClient(createConfig());

export const getSite = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<GetSiteData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetSiteResponse, GetSiteError, ThrowOnError>({
        ...options,
        url: '/api/v2/{siteKey}/public/site'
    });
};

export const getEvents = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<GetEventsData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetEventsResponse, GetEventsError, ThrowOnError>({
        ...options,
        url: '/api/v2/{siteKey}/public/events'
    });
};

/**
 * Get event dates and years
 * Returns all unique start dates and years for published events. Use 'upcoming' to filter to future events, and 'interval' to control date format (day, month, or year). Limited to processing the first 1000 events.
 */
export const getEventDates = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<GetEventDatesData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetEventDatesResponse, GetEventDatesError, ThrowOnError>({
        ...options,
        url: '/api/v2/{siteKey}/public/events/dates'
    });
};

export const getEvent = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<GetEventData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetEventResponse, GetEventError, ThrowOnError>({
        ...options,
        url: '/api/v2/{siteKey}/public/events/{slug}'
    });
};

export const getPages = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<GetPagesData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetPagesResponse, GetPagesError, ThrowOnError>({
        ...options,
        url: '/api/v2/{siteKey}/public/pages'
    });
};

export const getPage = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<GetPageData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetPageResponse, GetPageError, ThrowOnError>({
        ...options,
        url: '/api/v2/{siteKey}/public/pages/{slug}'
    });
};

export const getProfiles = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<GetProfilesData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetProfilesResponse, GetProfilesError, ThrowOnError>({
        ...options,
        url: '/api/v2/{siteKey}/public/profiles'
    });
};

export const getProfile = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<GetProfileData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetProfileResponse, GetProfileError, ThrowOnError>({
        ...options,
        url: '/api/v2/{siteKey}/public/profiles/{slug}'
    });
};

export const getProfileEvents = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<GetProfileEventsData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetProfileEventsResponse, GetProfileEventsError, ThrowOnError>({
        ...options,
        url: '/api/v2/{siteKey}/public/profiles/{slug}/events'
    });
};

export const getProducts = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<GetProductsData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetProductsResponse, GetProductsError, ThrowOnError>({
        ...options,
        url: '/api/v2/{siteKey}/public/products'
    });
};

export const getProduct = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<GetProductData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetProductResponse, GetProductError, ThrowOnError>({
        ...options,
        url: '/api/v2/{siteKey}/public/products/{slug}'
    });
};

export const searchSite = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<SearchSiteData, ThrowOnError>) => {
    return (options?.client ?? client).get<SearchSiteResponse, SearchSiteError, ThrowOnError>({
        ...options,
        url: '/api/v2/{siteKey}/public/search'
    });
};

export const getTags = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<GetTagsData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetTagsResponse, GetTagsError, ThrowOnError>({
        ...options,
        url: '/api/v2/{siteKey}/public/tags'
    });
};

export const listSiteDomains = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<ListSiteDomainsData, ThrowOnError>) => {
    return (options?.client ?? client).get<ListSiteDomainsResponse, ListSiteDomainsError, ThrowOnError>({
        ...options,
        url: '/api/v2/{siteKey}/public/domains'
    });
};

export const getSiteByDomain = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<GetSiteByDomainData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetSiteByDomainResponse, GetSiteByDomainError, ThrowOnError>({
        ...options,
        url: '/api/v2/{siteKey}/public/domain/{domain}'
    });
};

export const getEmailConfig = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<GetEmailConfigData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetEmailConfigResponse, GetEmailConfigError, ThrowOnError>({
        ...options,
        url: '/api/v2/{siteKey}/backend/email/config'
    });
};

export const updateEmailConfig = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<UpdateEmailConfigData, ThrowOnError>) => {
    return (options?.client ?? client).put<UpdateEmailConfigResponse, UpdateEmailConfigError, ThrowOnError>({
        ...options,
        url: '/api/v2/{siteKey}/backend/email/config'
    });
};

export const getDomainStatus = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<GetDomainStatusData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetDomainStatusResponse, GetDomainStatusError, ThrowOnError>({
        ...options,
        url: '/api/v2/{siteKey}/backend/email/domain'
    });
};

export const addCustomDomain = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<AddCustomDomainData, ThrowOnError>) => {
    return (options?.client ?? client).post<AddCustomDomainResponse, AddCustomDomainError, ThrowOnError>({
        ...options,
        url: '/api/v2/{siteKey}/backend/email/domain'
    });
};

export const removeCustomDomain = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<RemoveCustomDomainData, ThrowOnError>) => {
    return (options?.client ?? client).delete<RemoveCustomDomainResponse, RemoveCustomDomainError, ThrowOnError>({
        ...options,
        url: '/api/v2/{siteKey}/backend/email/domain'
    });
};

export const verifyDomain = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<VerifyDomainData, ThrowOnError>) => {
    return (options?.client ?? client).post<VerifyDomainResponse, VerifyDomainError, ThrowOnError>({
        ...options,
        url: '/api/v2/{siteKey}/backend/email/domain/verify'
    });
};

export const getEmails = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<GetEmailsData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetEmailsResponse, GetEmailsError, ThrowOnError>({
        ...options,
        url: '/api/v2/{siteKey}/backend/email/emails'
    });
};

export const getEmailStats = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<GetEmailStatsData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetEmailStatsResponse, GetEmailStatsError, ThrowOnError>({
        ...options,
        url: '/api/v2/{siteKey}/backend/email/emails/stats'
    });
};

export const getEmailById = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<GetEmailByIdData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetEmailByIdResponse, GetEmailByIdError, ThrowOnError>({
        ...options,
        url: '/api/v2/{siteKey}/backend/email/emails/:emailId'
    });
};

export const getEmailBatches = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<GetEmailBatchesData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetEmailBatchesResponse, GetEmailBatchesError, ThrowOnError>({
        ...options,
        url: '/api/v2/{siteKey}/backend/email/batches'
    });
};

export const createDraftBatch = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<CreateDraftBatchData, ThrowOnError>) => {
    return (options?.client ?? client).post<CreateDraftBatchResponse, CreateDraftBatchError, ThrowOnError>({
        ...options,
        url: '/api/v2/{siteKey}/backend/email/batches'
    });
};

export const getEmailBatch = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<GetEmailBatchData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetEmailBatchResponse, GetEmailBatchError, ThrowOnError>({
        ...options,
        url: '/api/v2/{siteKey}/backend/email/batches/:batchId'
    });
};

export const updateDraftBatch = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<UpdateDraftBatchData, ThrowOnError>) => {
    return (options?.client ?? client).put<UpdateDraftBatchResponse, UpdateDraftBatchError, ThrowOnError>({
        ...options,
        url: '/api/v2/{siteKey}/backend/email/batches/:batchId'
    });
};

export const deleteBatch = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<DeleteBatchData, ThrowOnError>) => {
    return (options?.client ?? client).delete<DeleteBatchResponse, DeleteBatchError, ThrowOnError>({
        ...options,
        url: '/api/v2/{siteKey}/backend/email/batches/:batchId'
    });
};

export const createAndSendBatch = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<CreateAndSendBatchData, ThrowOnError>) => {
    return (options?.client ?? client).post<CreateAndSendBatchResponse, CreateAndSendBatchError, ThrowOnError>({
        ...options,
        url: '/api/v2/{siteKey}/backend/email/batches/send'
    });
};

export const sendBatch = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<SendBatchData, ThrowOnError>) => {
    return (options?.client ?? client).post<SendBatchResponse, SendBatchError, ThrowOnError>({
        ...options,
        url: '/api/v2/{siteKey}/backend/email/batches/:batchId/send'
    });
};