// This file is auto-generated by @hey-api/openapi-ts

export type AddDomainInput = {
    domain: string;
};

export type AddDomainResponse = {
    domain: string;
    records: Array<DnsRecord>;
};

export type AddMediaItemToCollectionInput = {
    mediaItemId: string;
};

export type AddRoleToMediaCollectionInput = {
    roleId: string;
};

export type AddRoleToMediaItemInput = {
    roleId: string;
};

export type AtprotoOauthDisconnectResponse = {
    success: boolean;
};

export type AtprotoOauthStartInput = {
    /**
     * ATproto handle or DID to start OAuth for
     */
    handle?: string;
};

export type AtprotoOauthStartResponse = {
    authorizeUrl: string;
};

export type AtprotoOauthStatusResponse = {
    connected: boolean;
    did: (string) | null;
    handle: (string) | null;
    pdsUrl: (string) | null;
    needsReauth: boolean;
};

export type BatchEmail = {
    id: string;
    to: string;
    subject: (string) | null;
    status: 'PENDING' | 'SENT' | 'DELIVERED' | 'BOUNCED' | 'FAILED';
    createdAt: string;
    sentAt: (string) | null;
    errorMsg: (string) | null;
};

export type status = 'PENDING' | 'SENT' | 'DELIVERED' | 'BOUNCED' | 'FAILED';

export type BatchPagination = {
    page: number;
    limit: number;
    total: number;
    totalPages: number;
};

export type BatchSendResult = {
    batchId: string;
    status: 'COMPLETED';
    totalCount: number;
    sentCount: number;
    failedCount: number;
    results: Array<{
        emailId: string;
        to: string;
        status: 'PENDING' | 'SENT' | 'DELIVERED' | 'BOUNCED' | 'FAILED';
        resendId?: string;
        error?: string;
    }>;
};

export type status2 = 'COMPLETED';

export type CreateDraftBatchInput = {
    name?: string;
    templateKey?: string;
    subject?: string;
    recipients: Array<Recipient>;
};

export type CreateLivestreamInput = {
    title?: string;
    roleIds?: Array<(string)>;
};

export type CreateMediaCollectionInput = {
    name: string;
    description?: string;
    entityType?: 'event' | 'profile' | 'page' | 'location' | 'product';
    entityId?: string;
};

export type entityType = 'event' | 'profile' | 'page' | 'location' | 'product';

export type CustomSchemaData = {
    data?: unknown;
    customSchemaId?: (string) | null;
};

export type DnsRecord = {
    type: string;
    name: string;
    value: string;
    ttl?: string;
    priority?: number;
    status?: string;
};

export type DomainStatus = {
    verified: boolean;
    status?: string;
    records?: Array<DnsRecord>;
} | null;

export type DraftBatchResult = {
    batchId: string;
    status: 'DRAFT';
    recipientCount: number;
};

export type status3 = 'DRAFT';

export type Email = {
    id: string;
    siteId: string;
    batchId: string;
    createdAt: string;
    to: string;
    from: (string) | null;
    subject: (string) | null;
    templateKey: (string) | null;
    status: 'PENDING' | 'SENT' | 'DELIVERED' | 'BOUNCED' | 'FAILED';
    sentAt: (string) | null;
    resendId: (string) | null;
    errorMsg: (string) | null;
    batch: {
        id: string;
        name: (string) | null;
    } | null;
};

export type EmailBatch = {
    id: string;
    siteId: string;
    createdAt: string;
    name: (string) | null;
    templateKey: (string) | null;
    subject: (string) | null;
    status: 'DRAFT' | 'SENDING' | 'COMPLETED';
    totalCount: number;
    sentCount: number;
    failedCount: number;
    sentAt: (string) | null;
    completedAt: (string) | null;
};

export type status4 = 'DRAFT' | 'SENDING' | 'COMPLETED';

export type EmailBatchDetail = EmailBatch & {
    recipients?: Array<Recipient>;
    emails?: Array<BatchEmail>;
};

export type EmailBatchesResponse = {
    batches: Array<EmailBatch>;
    pagination: BatchPagination;
};

export type EmailConfig = {
    id: string;
    siteId: string;
    fromEmail: (string) | null;
    fromName: (string) | null;
    replyToEmail: (string) | null;
    customDomain: (string) | null;
    domainVerified: boolean;
    createdAt: string;
    updatedAt: string;
} | null;

export type EmailConfigInput = {
    fromEmail?: (string) | null;
    fromName?: (string) | null;
    replyToEmail?: (string) | null;
};

export type EmailsResponse = {
    emails: Array<Email>;
    pagination: Pagination;
};

export type EmailStats = {
    total: number;
    byStatus: {
        [key: string]: (number);
    };
    period: {
        days: number;
        since: string;
    };
};

export type EntityMediaCount = {
    count: number;
};

export type Event = {
    id: string;
    siteId: string;
    description?: (string) | null;
    slug: string;
    image?: MediaItem;
    startDate: (string);
    endDate: (string);
    hasTime: boolean;
    publishState: 'DRAFT' | 'REQUEST' | 'PUBLISHED' | 'CANCELLED';
    location?: LocationSlim;
    artists: Array<{
        profile: ProfileSlim;
    }>;
    tickets?: Array<TicketOnEvent>;
    tags?: Array<Tag>;
    custom?: Array<CustomSchemaData>;
    localizedContent: Array<LocalizedContent>;
    relations?: EventRelations;
};

export type publishState = 'DRAFT' | 'REQUEST' | 'PUBLISHED' | 'CANCELLED';

export type EventDates = {
    /**
     * Array of unique event dates. Format depends on interval: day (YYYY-MM-DD), month (YYYY-MM), or year (YYYY)
     */
    dates: Array<(string)>;
    /**
     * Array of unique years that have events
     */
    years: Array<(number)>;
};

export type EventReference = {
    id: string;
    slug: string;
    publishState?: string;
    startDate?: (string) | null;
    endDate?: (string) | null;
    localizedContent: Array<LocalizedContent>;
    image?: (MediaItem & unknown);
};

export type EventRelations = {
    parents?: Array<EventReference>;
    children?: Array<EventReference>;
};

export type LinkPreview = {
    url: string;
    meta?: {
        title?: string;
        description?: string;
        author?: string;
        site?: string;
    };
    html?: string;
    thumbnail_url?: string;
    provider_name?: string;
    provider_url?: string;
    error?: string;
};

export type LivestreamResponse = {
    mediaItem?: unknown;
    streamKey: string;
    rtmpUrl: string;
    playbackPolicy: 'public' | 'signed';
    muxLiveStreamId: string;
    muxPlaybackId: string;
    liveStatus?: 'idle' | 'active' | 'disabled';
};

export type playbackPolicy = 'public' | 'signed';

export type liveStatus = 'idle' | 'active' | 'disabled';

export type LocalizedContent = {
    siteId: string;
    locale: string;
    title?: (string) | null;
    content?: (string) | null;
    shortContent?: (string) | null;
    extraContent?: (string) | null;
    excerpt?: (string) | null;
    metaTitle?: (string) | null;
    metaDescription?: (string) | null;
    keywords?: (string) | null;
    contentJSON?: {
        [key: string]: unknown;
    } | null;
};

export type LocationSlim = {
    siteId: string;
    image?: MediaItem;
    address?: (string) | null;
    address2?: (string) | null;
    state?: (string) | null;
    region?: (string) | null;
    city?: (string) | null;
    zipCode?: (string) | null;
    country?: (string) | null;
    externalLink?: (string) | null;
    mapLink?: (string) | null;
    lat?: (number) | null;
    lng?: (number) | null;
    tags?: Array<Tag>;
    localizedContent: Array<LocalizedContent>;
    isDefault?: boolean;
};

export type MediaCollection = {
    id: string;
    siteId: string;
    name: string;
    description: (string) | null;
    entityType: (string) | null;
    entityId: (string) | null;
    createdAt: string;
    updatedAt: string;
    items?: Array<{
        mediaItemId: string;
        collectionId: string;
        order: number;
        mediaItem?: unknown;
    }>;
    roles?: Array<MediaCollectionRole>;
};

export type MediaCollectionRole = {
    mediaCollectionId: string;
    accessRoleId: string;
    accessRole: {
        id: string;
        name: (string) | null;
    };
};

export type MediaItem = {
    siteId: string;
    uploaded: boolean;
    inline: boolean;
    url?: (string) | null;
    mimeType?: (string) | null;
    size: string;
    width?: (number) | null;
    height?: (number) | null;
    duration?: (number) | null;
    metadata?: {
        [key: string]: unknown;
    } | null;
    title?: (string) | null;
    caption?: (string) | null;
    credit?: (string) | null;
    altText?: (string) | null;
};

export type MediaItemRole = {
    mediaItemId: string;
    accessRoleId: string;
    accessRole: {
        id: string;
        name: (string) | null;
    };
};

export type NewsDates = {
    /**
     * Array of unique news dates. Format depends on interval: day (YYYY-MM-DD), month (YYYY-MM), or year (YYYY)
     */
    dates: Array<(string)>;
    /**
     * Array of unique years that have news articles
     */
    years: Array<(number)>;
};

export type Page = {
    id: string;
    order: number;
    slug: string;
    featured: boolean;
    featuredExpiration?: (string | unknown);
    date?: (string | unknown);
    type: 'CONTENT' | 'NEWS' | 'LINK';
    linkUrl?: (string) | null;
    openInNewTab: boolean;
    parentId?: (string) | null;
    siteId: string;
    image?: MediaItem;
    parent?: {
        id: string;
        siteId: string;
        createdAt: string;
        updatedAt: string;
        recordType: 'SOURCE' | 'PUBLISHED' | 'REVISION';
        revisionId?: (number) | null;
        publishState: 'DRAFT' | 'REQUEST' | 'PUBLISHED' | 'CANCELLED';
        source?: (string) | null;
        publishedId?: (string) | null;
        dirty: boolean;
        order: number;
        visible: boolean;
        slug: string;
        featured: boolean;
        featuredExpiration?: (string) | null;
        date?: (string) | null;
        type: 'CONTENT' | 'NEWS' | 'LINK';
        linkUrl?: (string) | null;
        openInNewTab: boolean;
        imageId?: (string) | null;
        userId?: (string) | null;
        parentId?: (string) | null;
    };
    fullPath?: (string) | null;
    roles: Array<{
        pageId: string;
        accessRoleId: string;
        accessRole: {
            id: string;
            siteId: string;
            createdAt: string;
            updatedAt: string;
            name: string;
            description?: (string) | null;
        };
    }>;
    custom?: Array<CustomSchemaData>;
    tags?: Array<Tag>;
    localizedContent: Array<LocalizedContent>;
    artists?: Array<{
        profile: ProfileSlim;
    }>;
};

export type type = 'CONTENT' | 'NEWS' | 'LINK';

export type recordType = 'SOURCE' | 'PUBLISHED' | 'REVISION';

export type Pagination = {
    page: number;
    limit: number;
    total: number;
    totalPages: number;
};

export type PlaybackToken = {
    token: (string) | null;
};

export type Product = {
    siteId: string;
    slug: string;
    order: number;
    featured: boolean;
    featuredExpiration?: (string | unknown);
    author?: (string) | null;
    tags?: Array<Tag>;
    image?: MediaItem;
    localizedContent: Array<LocalizedContent>;
    artists: Array<{
        profile: ProfileSlim;
    }>;
    variants?: Array<ProductVariant>;
    custom?: Array<CustomSchemaData>;
};

export type ProductVariant = {
    id: string;
    siteId: string;
    order: number;
    price: number;
    currency?: (string) | null;
    quantity: number;
    externalLink?: (string) | null;
    catalogID?: (string) | null;
    publicationDate?: (string | unknown);
    productTypeId?: (string) | null;
    productId?: (string) | null;
    image?: (MediaItem & unknown);
    productType?: {
        id: string;
        type: string;
    } | null;
};

export type Profile = {
    siteId: string;
    slug: string;
    tags?: Array<Tag>;
    image?: MediaItem;
    localizedContent: Array<LocalizedContent>;
    custom?: Array<CustomSchemaData>;
};

export type ProfileSlim = {
    siteId: string;
    slug: string;
    tags?: Array<Tag>;
    image?: MediaItem;
    localizedContent: Array<LocalizedContent>;
    custom?: Array<CustomSchemaData>;
};

export type PublicLinkPreview = {
    url: string;
    meta?: {
        title?: string;
        description?: string;
        author?: string;
        site?: string;
    };
    html?: string;
    thumbnail_url?: string;
    provider_name?: string;
    provider_url?: string;
    error?: string;
};

export type Recipient = {
    email: string;
    subject?: string;
    variables?: {
        [key: string]: unknown;
    };
    metadata?: {
        [key: string]: unknown;
    };
};

export type ReorderMediaCollectionItemInput = {
    mediaItemId: string;
    upperNeighbor: (string) | null;
};

export type SearchAllSiteResults = {
    records: Array<{
        id: string;
        type: 'event' | 'page' | 'profile' | 'product';
        slug: string;
        siteId: string;
        image?: (MediaItem & unknown);
        localizedContent: Array<{
            locale: string;
            title?: (string) | null;
            shortContent?: (string) | null;
            content?: (string) | null;
        }>;
        startDate?: (string) | null;
        endDate?: (string) | null;
        similarity: number;
    }>;
};

export type SearchSiteResults = {
    events: Array<{
        id: string;
        image?: (MediaItem & unknown);
        localizedContent: Array<{
            locale: string;
            title?: (string) | null;
            shortContent?: (string) | null;
            content?: (string) | null;
        }>;
        siteId: string;
        slug: string;
    }>;
    pages: Array<{
        id: string;
        image?: (MediaItem & unknown);
        localizedContent: Array<{
            locale: string;
            title?: (string) | null;
            shortContent?: (string) | null;
            content?: (string) | null;
        }>;
        siteId: string;
        slug: string;
    }>;
    profiles: Array<{
        id: string;
        image?: (MediaItem & unknown);
        localizedContent: Array<{
            locale: string;
            title?: (string) | null;
            shortContent?: (string) | null;
            content?: (string) | null;
        }>;
        siteId: string;
        slug: string;
    }>;
    products: Array<{
        id: string;
        image?: (MediaItem & unknown);
        localizedContent: Array<{
            locale: string;
            title?: (string) | null;
            shortContent?: (string) | null;
            content?: (string) | null;
        }>;
        siteId: string;
        slug: string;
    }>;
};

export type Site = {
    id: string;
    name?: (string) | null;
    description?: (string) | null;
    defaultLocale?: (string) | null;
    timeZone?: (string) | null;
    image?: MediaItem;
    settings: SiteSettings;
    webSites?: Array<WebSite>;
};

export type SiteSettings = {
    locale?: {
        default: string;
        supported: Array<(string)>;
    };
    defaults?: {
        currency?: string;
        event?: {
            location?: string;
        };
    };
    publicSite?: {
        baseUrl?: string;
        template?: {
            id?: string;
            config?: {
                [key: string]: unknown;
            };
            schema?: {
                [key: string]: unknown;
            };
        };
    };
};

export type StopLivestreamResponse = {
    mediaItem?: unknown;
    liveStatus: 'idle' | 'active' | 'disabled' | 'completed';
};

export type liveStatus2 = 'idle' | 'active' | 'disabled' | 'completed';

export type Tag = {
    tagId: string;
    tag: {
        id: string;
        siteId: string;
        title: string;
        parentTags?: Array<{
            tagId: string;
            parentTagId: string;
            createdAt: (string);
            parentTag: {
                id: string;
                siteId: string;
                title: string;
            };
        }>;
    };
};

export type TagListItem = {
    id: string;
    siteId: string;
    title: string;
    parentTags?: Array<{
        tagId: string;
        parentTagId: string;
        createdAt: (string);
        parentTag: {
            id: string;
            siteId: string;
            title: string;
        };
    }>;
};

export type TicketOnEvent = {
    name: string;
    price: number;
    externalLink?: (string) | null;
    currency?: (string) | null;
    roles: Array<unknown>;
    localizedContent?: Array<LocalizedContent>;
    order?: number;
};

export type UpdatedMediaItem = {
    id: string;
    title?: (string) | null;
    caption?: (string) | null;
    credit?: (string) | null;
    altText?: (string) | null;
};

export type UpdateDraftBatchInput = {
    name?: string;
    templateKey?: string;
    subject?: string;
    recipients?: Array<Recipient>;
};

export type UpdateMediaCollectionInput = {
    name?: string;
    description?: (string) | null;
};

export type UpdateMediaItemInput = {
    title?: (string) | null;
    caption?: (string) | null;
    credit?: (string) | null;
    altText?: (string) | null;
};

export type UpdateMediaItemOrderInput = {
    entityType: 'event' | 'profile' | 'page' | 'location' | 'product';
    entityId: string;
    mediaItemId: string;
    upperNeighbor: (string) | null;
};

export type UpdateMediaItemOrderResponse = {
    itemIds: Array<(string)>;
};

export type WebSite = {
    id: string;
    siteId: string;
    customDomain?: (string) | null;
    customSchemaId?: (string) | null;
    config?: {
        [key: string]: unknown;
    } | null;
    image?: (MediaItem & unknown);
    localizedContent?: Array<LocalizedContent> | null;
};

export type PublicSignInData = {
    body?: {
        email: string;
        password: string;
        captchaToken?: string;
    };
    path: {
        siteKey: string;
    };
};

export type PublicSignInResponse = ({
    session: {
        access_token: string;
        refresh_token: string;
        expires_in: number;
        token_type: string;
    };
    user: {
        id: string;
        email?: string;
    };
});

export type PublicSignInError = ({
    error: string;
});

export type PublicSignOutData = {
    path: {
        siteKey: string;
    };
};

export type PublicSignOutResponse = ({
    success: boolean;
});

export type PublicSignOutError = unknown;

export type PublicSignUpData = {
    body?: {
        email: string;
        password: string;
        captchaToken?: string;
    };
    path: {
        siteKey: string;
    };
};

export type PublicSignUpResponse = ({
    user: {
        id: string;
        email?: string;
    };
    confirmEmail: boolean;
});

export type PublicSignUpError = ({
    error: string;
});

export type GetSiteData = {
    path: {
        siteKey: string;
    };
};

export type GetSiteResponse = (Site);

export type GetSiteError = (unknown);

export type GetEventsData = {
    path: {
        siteKey: string;
    };
    query?: {
        dir?: 'asc' | 'desc';
        featured?: (boolean) | null;
        gt?: (number) | null;
        legacyId?: string;
        limit?: (number) | null;
        lt?: (number) | null;
        orderBy?: string;
        page?: (number) | null;
        query?: (string) | null;
        rootOnly?: (boolean) | null;
        tags?: (string | Array<(string)>);
        upcoming?: (boolean) | null;
    };
};

export type GetEventsResponse = ({
    records: Array<Event>;
    count: number;
});

export type GetEventsError = unknown;

export type GetEventDatesData = {
    path: {
        siteKey: string;
    };
    query?: {
        gt?: (number) | null;
        interval?: 'day' | 'month' | 'year';
        lt?: (number) | null;
        upcoming?: (boolean) | null;
    };
};

export type GetEventDatesResponse = (EventDates);

export type GetEventDatesError = unknown;

export type GetEventData = {
    path: {
        siteKey: string;
        slug: string;
    };
};

export type GetEventResponse = (Event);

export type GetEventError = (unknown);

export type GetNewsData = {
    path: {
        siteKey: string;
    };
    query?: {
        dir?: 'asc' | 'desc';
        featured?: (boolean) | null;
        gt?: (number) | null;
        limit?: (number) | null;
        lt?: (number) | null;
        orderBy?: string;
        page?: (number) | null;
        query?: (string) | null;
        tags?: (string | Array<(string)>);
        upcoming?: (boolean) | null;
    };
};

export type GetNewsResponse = ({
    records: Array<(Page & {
    parent?: {
        [key: string]: unknown;
    };
})>;
    count: number;
});

export type GetNewsError = unknown;

export type GetNewsDatesData = {
    path: {
        siteKey: string;
    };
    query?: {
        gt?: (number) | null;
        interval?: 'day' | 'month' | 'year';
        lt?: (number) | null;
    };
};

export type GetNewsDatesResponse = (NewsDates);

export type GetNewsDatesError = unknown;

export type GetNewsArticleData = {
    path: {
        siteKey: string;
        slug: string;
    };
};

export type GetNewsArticleResponse = ((Page & {
    parent?: {
        [key: string]: unknown;
    };
}));

export type GetNewsArticleError = (unknown);

export type GetPagesData = {
    path: {
        siteKey: string;
    };
    query?: {
        dir?: 'asc' | 'desc';
        featured?: (boolean) | null;
        limit?: (number) | null;
        orderBy?: string;
        page?: (number) | null;
        query?: (string) | null;
        tags?: (string | Array<(string)>);
    };
};

export type GetPagesResponse = ({
    records: Array<(Page & {
    parent?: {
        [key: string]: unknown;
    };
})>;
    count: number;
});

export type GetPagesError = unknown;

export type GetPageData = {
    path: {
        siteKey: string;
        slug: string;
    };
};

export type GetPageResponse = ((Page & {
    parent?: {
        [key: string]: unknown;
    };
}));

export type GetPageError = (unknown);

export type GetProfilesData = {
    path: {
        siteKey: string;
    };
    query?: {
        dir?: 'asc' | 'desc';
        limit?: (number) | null;
        orderBy?: string;
        page?: (number) | null;
        query?: (string) | null;
        tags?: (string | Array<(string)>);
        type?: 'member';
    };
};

export type GetProfilesResponse = ({
    records: Array<Profile>;
    count?: number;
});

export type GetProfilesError = unknown;

export type GetProfileData = {
    path: {
        siteKey: string;
        slug: string;
    };
};

export type GetProfileResponse = (Profile);

export type GetProfileError = (unknown);

export type GetProfileEventsData = {
    path: {
        siteKey: string;
        slug: string;
    };
    query?: {
        dir?: 'asc' | 'desc';
        featured?: (boolean) | null;
        gt?: (number) | null;
        legacyId?: string;
        limit?: (number) | null;
        lt?: (number) | null;
        orderBy?: string;
        page?: (number) | null;
        query?: (string) | null;
        rootOnly?: (boolean) | null;
        tags?: (string | Array<(string)>);
        upcoming?: (boolean) | null;
    };
};

export type GetProfileEventsResponse = ({
    records: Array<Event>;
    count?: number;
});

export type GetProfileEventsError = (unknown);

export type GetProfileProductsData = {
    path: {
        siteKey: string;
        slug: string;
    };
    query?: {
        dir?: 'asc' | 'desc';
        featured?: 'true' | 'false';
        limit?: (number) | null;
        orderBy?: string;
        page?: (number) | null;
    };
};

export type GetProfileProductsResponse = ({
    records: Array<Product>;
    count: number;
});

export type GetProfileProductsError = (unknown);

export type GetProductsData = {
    path: {
        siteKey: string;
    };
    query?: {
        dir?: 'asc' | 'desc';
        limit?: (number) | null;
        orderBy?: string;
        page?: (number) | null;
        query?: (string) | null;
        tags?: (string | Array<(string)>);
        type?: 'member';
    };
};

export type GetProductsResponse = ({
    records: Array<Product>;
    count?: number;
});

export type GetProductsError = unknown;

export type GetProductData = {
    path: {
        siteKey: string;
        slug: string;
    };
};

export type GetProductResponse = (Product);

export type GetProductError = (unknown);

export type SearchSiteData = {
    path: {
        siteKey: string;
    };
    query?: {
        debug?: 'true' | 'false' | '1' | '0';
        dir?: 'asc' | 'desc';
        disableVector?: 'true' | 'false' | '1' | '0';
        limit?: (number) | null;
        minResultSimilarity?: (number) | null;
        noCache?: 'true' | 'false' | '1' | '0';
        orderBy?: string;
        page?: (number) | null;
        query?: (string) | null;
        searchProvider?: ('algolia' | 'trigram' | 'hybrid') | null;
        trigramThreshold?: (number) | null;
        vectorThreshold?: (number) | null;
    };
};

export type SearchSiteResponse = (SearchSiteResults);

export type SearchSiteError = (unknown);

export type SearchAllData = {
    path: {
        siteKey: string;
    };
    query?: {
        debug?: 'true' | 'false' | '1' | '0';
        dir?: 'asc' | 'desc';
        disableVector?: 'true' | 'false' | '1' | '0';
        limit?: (number) | null;
        minResultSimilarity?: (number) | null;
        noCache?: 'true' | 'false' | '1' | '0';
        orderBy?: string;
        page?: (number) | null;
        query?: (string) | null;
        searchProvider?: ('algolia' | 'trigram' | 'hybrid') | null;
        trigramThreshold?: (number) | null;
        vectorThreshold?: (number) | null;
    };
};

export type SearchAllResponse = (SearchAllSiteResults);

export type SearchAllError = (unknown);

export type GetTagsData = {
    path: {
        siteKey: string;
    };
    query?: {
        dir?: 'asc' | 'desc';
        limit?: (number) | null;
        orderBy?: string;
        page?: (number) | null;
        parentId?: string;
        query?: string;
    };
};

export type GetTagsResponse = ({
    records: Array<TagListItem>;
    count?: number;
});

export type GetTagsError = unknown;

export type GetPublicLinkPreviewData = {
    path: {
        siteKey: string;
    };
    query: {
        url: string;
    };
};

export type GetPublicLinkPreviewResponse = (PublicLinkPreview);

export type GetPublicLinkPreviewError = (unknown);

export type GetPlaybackTokenData = {
    path: {
        mediaItemId: string;
        siteKey: string;
    };
};

export type GetPlaybackTokenResponse = (PlaybackToken);

export type GetPlaybackTokenError = (unknown);

export type ListSiteDomainsData = {
    path: {
        siteKey: string;
    };
};

export type ListSiteDomainsResponse = ({
    records: Array<{
        siteKey: string;
        customDomain: string;
    }>;
});

export type ListSiteDomainsError = unknown;

export type GetSiteByDomainData = {
    path: {
        domain: string;
        siteKey: string;
    };
};

export type GetSiteByDomainResponse = ({
    id: string;
    siteKey: string;
});

export type GetSiteByDomainError = (unknown);

export type GetEmailConfigData = {
    path: {
        siteKey: string;
    };
};

export type GetEmailConfigResponse = (EmailConfig);

export type GetEmailConfigError = (unknown);

export type UpdateEmailConfigData = {
    body?: EmailConfigInput;
    path: {
        siteKey: string;
    };
};

export type UpdateEmailConfigResponse = (EmailConfig);

export type UpdateEmailConfigError = (unknown);

export type GetDomainStatusData = {
    path: {
        siteKey: string;
    };
};

export type GetDomainStatusResponse = (DomainStatus);

export type GetDomainStatusError = (unknown);

export type AddCustomDomainData = {
    body?: AddDomainInput;
    path: {
        siteKey: string;
    };
};

export type AddCustomDomainResponse = (AddDomainResponse);

export type AddCustomDomainError = (unknown);

export type RemoveCustomDomainData = {
    path: {
        siteKey: string;
    };
};

export type RemoveCustomDomainResponse = ({
    success: boolean;
});

export type RemoveCustomDomainError = (unknown);

export type VerifyDomainData = {
    path: {
        siteKey: string;
    };
};

export type VerifyDomainResponse = (DomainStatus);

export type VerifyDomainError = (unknown);

export type GetEmailsData = {
    path: {
        siteKey: string;
    };
    query?: {
        batchId?: string;
        endDate?: string;
        limit?: string;
        page?: string;
        startDate?: string;
        status?: 'PENDING' | 'SENT' | 'DELIVERED' | 'BOUNCED' | 'FAILED';
        templateKey?: string;
    };
};

export type GetEmailsResponse = (EmailsResponse);

export type GetEmailsError = (unknown);

export type GetEmailStatsData = {
    path: {
        siteKey: string;
    };
    query?: {
        days?: string;
    };
};

export type GetEmailStatsResponse = (EmailStats);

export type GetEmailStatsError = (unknown);

export type GetEmailByIdData = {
    path: {
        emailId: string;
        siteKey: string;
    };
};

export type GetEmailByIdResponse = (Email);

export type GetEmailByIdError = (unknown);

export type GetEmailBatchesData = {
    path: {
        siteKey: string;
    };
    query?: {
        endDate?: string;
        limit?: string;
        page?: string;
        startDate?: string;
        status?: 'DRAFT' | 'SENDING' | 'COMPLETED';
        templateKey?: string;
    };
};

export type GetEmailBatchesResponse = (EmailBatchesResponse);

export type GetEmailBatchesError = (unknown);

export type CreateDraftBatchData = {
    body?: CreateDraftBatchInput;
    path: {
        siteKey: string;
    };
};

export type CreateDraftBatchResponse = (DraftBatchResult);

export type CreateDraftBatchError = (unknown);

export type GetEmailBatchData = {
    path: {
        batchId: string;
        siteKey: string;
    };
};

export type GetEmailBatchResponse = (EmailBatchDetail);

export type GetEmailBatchError = (unknown);

export type UpdateDraftBatchData = {
    body?: UpdateDraftBatchInput;
    path: {
        batchId: string;
        siteKey: string;
    };
};

export type UpdateDraftBatchResponse = ({
    updated: boolean;
});

export type UpdateDraftBatchError = (unknown);

export type DeleteBatchData = {
    path: {
        batchId: string;
        siteKey: string;
    };
};

export type DeleteBatchResponse = ({
    deleted: boolean;
});

export type DeleteBatchError = (unknown);

export type CreateAndSendBatchData = {
    body?: CreateDraftBatchInput;
    path: {
        siteKey: string;
    };
};

export type CreateAndSendBatchResponse = (BatchSendResult);

export type CreateAndSendBatchError = (unknown);

export type SendBatchData = {
    path: {
        batchId: string;
        siteKey: string;
    };
};

export type SendBatchResponse = (BatchSendResult);

export type SendBatchError = (unknown);

export type UpdateMediaItemOrderData = {
    body?: UpdateMediaItemOrderInput;
    path: {
        siteKey: string;
    };
};

export type UpdateMediaItemOrderResponse2 = (UpdateMediaItemOrderResponse);

export type UpdateMediaItemOrderError = (unknown);

export type ListMediaItemRolesData = {
    path: {
        mediaItemId: string;
        siteKey: string;
    };
};

export type ListMediaItemRolesResponse = (Array<MediaItemRole>);

export type ListMediaItemRolesError = (unknown);

export type AddRoleToMediaItemData = {
    body?: AddRoleToMediaItemInput;
    path: {
        mediaItemId: string;
        siteKey: string;
    };
};

export type AddRoleToMediaItemResponse = (Array<MediaItemRole>);

export type AddRoleToMediaItemError = (unknown);

export type RemoveRoleFromMediaItemData = {
    path: {
        mediaItemId: string;
        roleId: string;
        siteKey: string;
    };
};

export type RemoveRoleFromMediaItemResponse = (Array<MediaItemRole>);

export type RemoveRoleFromMediaItemError = (unknown);

export type UpdateMediaItemData = {
    body?: UpdateMediaItemInput;
    path: {
        mediaItemId: string;
        siteKey: string;
    };
};

export type UpdateMediaItemResponse = (UpdatedMediaItem);

export type UpdateMediaItemError = (unknown);

export type DeleteMediaItemData = {
    path: {
        mediaItemId: string;
        siteKey: string;
    };
};

export type DeleteMediaItemResponse = ({
    success: boolean;
});

export type DeleteMediaItemError = (unknown);

export type ListMediaCollectionsData = {
    path: {
        siteKey: string;
    };
    query?: {
        entityId?: string;
        entityType?: 'event' | 'profile' | 'page' | 'location' | 'product';
    };
};

export type ListMediaCollectionsResponse = (Array<MediaCollection>);

export type ListMediaCollectionsError = unknown;

export type CreateMediaCollectionData = {
    body?: CreateMediaCollectionInput;
    path: {
        siteKey: string;
    };
};

export type CreateMediaCollectionResponse = (MediaCollection);

export type CreateMediaCollectionError = (unknown);

export type GetMediaCollectionData = {
    path: {
        collectionId: string;
        siteKey: string;
    };
};

export type GetMediaCollectionResponse = (MediaCollection);

export type GetMediaCollectionError = (unknown);

export type UpdateMediaCollectionData = {
    body?: UpdateMediaCollectionInput;
    path: {
        collectionId: string;
        siteKey: string;
    };
};

export type UpdateMediaCollectionResponse = (MediaCollection);

export type UpdateMediaCollectionError = (unknown);

export type DeleteMediaCollectionData = {
    path: {
        collectionId: string;
        siteKey: string;
    };
};

export type DeleteMediaCollectionResponse = ({
    ok: boolean;
});

export type DeleteMediaCollectionError = (unknown);

export type AddItemToMediaCollectionData = {
    body?: AddMediaItemToCollectionInput;
    path: {
        collectionId: string;
        siteKey: string;
    };
};

export type AddItemToMediaCollectionResponse = (MediaCollection);

export type AddItemToMediaCollectionError = (unknown);

export type ReorderMediaCollectionItemData = {
    body?: ReorderMediaCollectionItemInput;
    path: {
        collectionId: string;
        siteKey: string;
    };
};

export type ReorderMediaCollectionItemResponse = (MediaCollection);

export type ReorderMediaCollectionItemError = (unknown);

export type RemoveItemFromMediaCollectionData = {
    path: {
        collectionId: string;
        mediaItemId: string;
        siteKey: string;
    };
    query?: {
        ensureEntityId?: string;
        ensureEntityType?: 'event' | 'profile' | 'page' | 'location' | 'product';
    };
};

export type RemoveItemFromMediaCollectionResponse = (MediaCollection);

export type RemoveItemFromMediaCollectionError = (unknown);

export type ListMediaCollectionRolesData = {
    path: {
        collectionId: string;
        siteKey: string;
    };
};

export type ListMediaCollectionRolesResponse = (Array<MediaCollectionRole>);

export type ListMediaCollectionRolesError = (unknown);

export type AddRoleToMediaCollectionData = {
    body?: AddRoleToMediaCollectionInput;
    path: {
        collectionId: string;
        siteKey: string;
    };
};

export type AddRoleToMediaCollectionResponse = (Array<MediaCollectionRole>);

export type AddRoleToMediaCollectionError = (unknown);

export type RemoveRoleFromMediaCollectionData = {
    path: {
        collectionId: string;
        roleId: string;
        siteKey: string;
    };
};

export type RemoveRoleFromMediaCollectionResponse = (Array<MediaCollectionRole>);

export type RemoveRoleFromMediaCollectionError = (unknown);

export type GetEntityMediaCountData = {
    path: {
        entityId: string;
        entityType: 'event' | 'profile' | 'page' | 'location' | 'product';
        siteKey: string;
    };
};

export type GetEntityMediaCountResponse = (EntityMediaCount);

export type GetEntityMediaCountError = (unknown);

export type GetBackendLinkPreviewData = {
    path: {
        siteKey: string;
    };
    query: {
        url: string;
    };
};

export type GetBackendLinkPreviewResponse = (LinkPreview);

export type GetBackendLinkPreviewError = (unknown);

export type AtprotoOauthStartData = {
    body?: AtprotoOauthStartInput;
    path: {
        siteKey: string;
    };
};

export type AtprotoOauthStartResponse2 = (AtprotoOauthStartResponse);

export type AtprotoOauthStartError = (unknown);

export type AtprotoOauthDisconnectData = {
    path: {
        siteKey: string;
    };
};

export type AtprotoOauthDisconnectResponse2 = (AtprotoOauthDisconnectResponse);

export type AtprotoOauthDisconnectError = (unknown);

export type AtprotoOauthStatusData = {
    path: {
        siteKey: string;
    };
};

export type AtprotoOauthStatusResponse2 = (AtprotoOauthStatusResponse);

export type AtprotoOauthStatusError = (unknown);

export type CreateEventLivestreamData = {
    body?: CreateLivestreamInput;
    path: {
        eventId: string;
        siteKey: string;
    };
};

export type CreateEventLivestreamResponse = (LivestreamResponse);

export type CreateEventLivestreamError = (unknown);

export type GetEventLivestreamData = {
    path: {
        mediaItemId: string;
        siteKey: string;
    };
};

export type GetEventLivestreamResponse = (LivestreamResponse);

export type GetEventLivestreamError = (unknown);

export type DeleteEventLivestreamData = {
    path: {
        mediaItemId: string;
        siteKey: string;
    };
};

export type DeleteEventLivestreamResponse = ({
    success: boolean;
});

export type DeleteEventLivestreamError = (unknown);

export type StopEventLivestreamData = {
    path: {
        mediaItemId: string;
        siteKey: string;
    };
};

export type StopEventLivestreamResponse = (StopLivestreamResponse);

export type StopEventLivestreamError = (unknown);