// This file is auto-generated by @hey-api/openapi-ts

export type AccessRole = {
    id: string;
    name: (string) | null;
};

export type AddDomainInput = {
    domain: string;
};

export type AddDomainResponse = {
    domain: string;
    records: Array<DnsRecord>;
};

export type AddImageResponse = {
    [key: string]: unknown;
};

export type AddImageToNoteInput = {
    fileName: string;
    mimeType: string;
    size: number;
    contentHash?: string;
    metadata?: {
        [key: string]: unknown;
    };
    isMainImage?: boolean;
    title?: string;
    caption?: string;
    credit?: string;
    altText?: string;
};

export type AddImageToNoteResponse = {
    uploadUrl: (string) | null;
    url?: (string) | null;
};

export type AddImageToUserInput = {
    fileName: string;
    mimeType: string;
    size: number;
    contentHash?: string;
    metadata?: {
        [key: string]: unknown;
    };
    title?: string;
    caption?: string;
    credit?: string;
    altText?: string;
    isMainImage?: boolean;
};

export type AddLocaleInput = {
    locale: string;
};

export type AddLocaleToLocationInput = {
    locale: string;
};

export type AddLocaleToPageInput = {
    locale: string;
};

export type AddLocaleToProductInput = {
    locale: string;
};

export type AddMediaItemToCollectionInput = {
    mediaItemId: string;
};

export type AddPageImageResponse = {
    [key: string]: unknown;
};

export type AddParentToPageInput = {
    parentId: string;
};

export type AddProductImageResponse = {
    [key: string]: unknown;
};

export type AddProfileToEventInput = {
    profileId: string;
};

export type AddProfileToPageInput = {
    profileId: string;
};

export type AddProfileToProductInput = {
    profileId: string;
};

export type AddRoleToMediaCollectionInput = {
    roleId: string;
};

export type AddRoleToMediaItemInput = {
    roleId: string;
};

export type AddRoleToPageInput = {
    roleId: string;
};

export type AddRoleToUserInput = {
    roleId: string;
};

export type AddUserToProfileInput = {
    userId: string;
};

export type AtprotoOauthDisconnectResponse = {
    success: boolean;
};

export type AtprotoOauthStartInput = {
    /**
     * ATproto handle or DID to start OAuth for
     */
    handle?: string;
};

export type AtprotoOauthStartResponse = {
    authorizeUrl: string;
};

export type AtprotoOauthStatusResponse = {
    connected: boolean;
    did: (string) | null;
    handle: (string) | null;
    pdsUrl: (string) | null;
    needsReauth: boolean;
};

export type AtprotoSettingsInput = {
    publishEnabled: boolean;
};

export type AtprotoSettingsResponse = {
    publishEnabled: boolean;
};

export type AttacheventsToTagInput = {
    eventId: string;
};

export type AttachpagesToTagInput = {
    pageId: string;
};

export type AttachproductsToTagInput = {
    productId: string;
};

export type AttachprofilesToTagInput = {
    profileId: string;
};

export type AttachTagRelationResponse = {
    record: {
        [key: string]: unknown;
    };
};

export type BatchEmail = {
    id: string;
    to: string;
    subject: (string) | null;
    status: 'PENDING' | 'SENT' | 'DELIVERED' | 'BOUNCED' | 'FAILED';
    createdAt: string;
    sentAt: (string) | null;
    errorMsg: (string) | null;
};

export type status = 'PENDING' | 'SENT' | 'DELIVERED' | 'BOUNCED' | 'FAILED';

export type BatchPagination = {
    page: number;
    limit: number;
    total: number;
    totalPages: number;
};

export type BatchSendResult = {
    batchId: string;
    status: 'COMPLETED';
    totalCount: number;
    sentCount: number;
    failedCount: number;
    results: Array<{
        emailId: string;
        to: string;
        status: 'PENDING' | 'SENT' | 'DELIVERED' | 'BOUNCED' | 'FAILED';
        resendId?: string;
        error?: string;
    }>;
};

export type status2 = 'COMPLETED';

export type BustCacheResponse = {
    results?: Array<{
        key: string;
        status: number;
    }>;
    error?: string;
};

export type CreateDraftBatchInput = {
    name?: string;
    templateKey?: string;
    subject?: string;
    recipients: Array<Recipient>;
};

export type CreateEventInput = {
    title?: string;
    startDate?: string;
    endDate?: string;
    content?: string;
    locale?: string;
};

export type CreateLivestreamInput = {
    title?: string;
    roleIds?: Array<(string)>;
};

export type CreateLocationInput = {
    [key: string]: unknown;
};

export type CreateMediaCollectionInput = {
    name: string;
    description?: string;
    entityType?: 'event' | 'profile' | 'page' | 'location' | 'product';
    entityId?: string;
};

export type entityType = 'event' | 'profile' | 'page' | 'location' | 'product';

export type CreatePageInput = {
    parentId?: string;
    date?: string;
    type?: 'CONTENT' | 'NEWS' | 'NEWSLIST' | 'EVENTLIST' | 'PROFILELIST' | 'PRODUCTLIST' | 'LINK';
};

export type type = 'CONTENT' | 'NEWS' | 'NEWSLIST' | 'EVENTLIST' | 'PROFILELIST' | 'PRODUCTLIST' | 'LINK';

export type CreateProfileInput = {
    title?: string;
    content?: string;
    shortContent?: string;
    eventId?: string;
};

export type CreateSimulcastTargetInput = {
    label: string;
    rtmpUrl: string;
    streamKey: string;
    ephemeral?: boolean;
};

export type CreateSiteApiKeyInput = {
    name: string;
};

export type CreateSiteApiKeyResponse = {
    key: string;
    record: SiteApiKey;
};

export type CreateTagInput = {
    tag: string;
};

export type CreateTicketInput = {
    name?: string;
    price?: (number) | null;
    currency?: (string) | null;
    localizedContent?: Array<{
        locale: string;
        title?: (string) | null;
        content?: (string) | null;
    }>;
    roleIds?: Array<(string)>;
};

export type CreateUserInput = {
    email: string;
    name?: string;
};

export type CustomSchemaData = {
    data?: unknown;
    customSchemaId?: (string) | null;
};

export type DeleteResponse = {
    ok: boolean;
};

export type DetachMediaItemInput = {
    entityType: 'event' | 'profile' | 'page' | 'location' | 'product';
    entityId: string;
    mediaItemId: string;
};

export type DetachMediaItemResponse = {
    success: boolean;
};

export type DnsRecord = {
    type: string;
    name: string;
    value: string;
    ttl?: string;
    priority?: number;
    status?: string;
};

export type DomainStatus = {
    verified: boolean;
    status?: string;
    records?: Array<DnsRecord>;
} | null;

export type DraftBatchResult = {
    batchId: string;
    status: 'DRAFT';
    recipientCount: number;
};

export type status3 = 'DRAFT';

export type Email = {
    id: string;
    siteId: string;
    batchId: string;
    createdAt: string;
    to: string;
    from: (string) | null;
    subject: (string) | null;
    templateKey: (string) | null;
    status: 'PENDING' | 'SENT' | 'DELIVERED' | 'BOUNCED' | 'FAILED';
    sentAt: (string) | null;
    resendId: (string) | null;
    errorMsg: (string) | null;
    batch: {
        id: string;
        name: (string) | null;
    } | null;
};

export type EmailBatch = {
    id: string;
    siteId: string;
    createdAt: string;
    name: (string) | null;
    templateKey: (string) | null;
    subject: (string) | null;
    status: 'DRAFT' | 'SENDING' | 'COMPLETED';
    totalCount: number;
    sentCount: number;
    failedCount: number;
    sentAt: (string) | null;
    completedAt: (string) | null;
};

export type status4 = 'DRAFT' | 'SENDING' | 'COMPLETED';

export type EmailBatchDetail = EmailBatch & {
    recipients?: Array<Recipient>;
    emails?: Array<BatchEmail>;
};

export type EmailBatchesResponse = {
    batches: Array<EmailBatch>;
    pagination: BatchPagination;
};

export type EmailConfig = {
    id: string;
    siteId: string;
    fromEmail: (string) | null;
    fromName: (string) | null;
    replyToEmail: (string) | null;
    customDomain: (string) | null;
    domainVerified: boolean;
    createdAt: string;
    updatedAt: string;
} | null;

export type EmailConfigInput = {
    fromEmail?: (string) | null;
    fromName?: (string) | null;
    replyToEmail?: (string) | null;
};

export type EmailsResponse = {
    emails: Array<Email>;
    pagination: Pagination;
};

export type EmailStats = {
    total: number;
    byStatus: {
        [key: string]: (number);
    };
    period: {
        days: number;
        since: string;
    };
};

export type EntityMediaCount = {
    count: number;
};

export type EntityMediaItems = {
    records: Array<{
        mediaItemId: string;
        mediaItem?: unknown;
    }>;
    count: number;
};

export type Event = {
    id: string;
    siteId: string;
    description?: (string) | null;
    slug: string;
    image?: MediaItem;
    startDate: (string);
    endDate: (string);
    hasTime: boolean;
    publishState: 'DRAFT' | 'REQUEST' | 'PUBLISHED' | 'CANCELLED';
    location?: LocationSlim;
    artists: Array<{
        profile: ProfileSlim;
    }>;
    tickets?: Array<TicketOnEvent>;
    tags?: Array<Tag>;
    custom?: Array<CustomSchemaData>;
    localizedContent: Array<LocalizedContent>;
    relations?: EventRelations;
    jsonLd?: {
        [key: string]: unknown;
    } | null;
    ogImageUrl?: (string) | null;
};

export type publishState = 'DRAFT' | 'REQUEST' | 'PUBLISHED' | 'CANCELLED';

export type EventDates = {
    /**
     * Array of unique event dates. Format depends on interval: day (YYYY-MM-DD), month (YYYY-MM), or year (YYYY)
     */
    dates: Array<(string)>;
    /**
     * Array of unique years that have events
     */
    years: Array<(number)>;
};

export type EventProfiles = {
    artists: Array<unknown>;
};

export type EventRecord = {
    id: string;
    siteId: string;
};

export type EventReference = {
    id: string;
    slug: string;
    publishState?: string;
    startDate?: (string) | null;
    endDate?: (string) | null;
    localizedContent: Array<LocalizedContent>;
    image?: (MediaItem & unknown);
};

export type EventRelationInput = {
    relationType: 'CHILD_OF';
    sourceId?: string;
    targetId?: string;
};

export type relationType = 'CHILD_OF';

export type EventRelations = {
    parents?: Array<EventReference>;
    children?: Array<EventReference>;
};

export type EventTagsResponse = {
    records: Array<{
        [key: string]: unknown;
    }>;
};

export type GoogleOauthDisconnectResponse = {
    success: boolean;
};

export type GoogleOauthStartResponse = {
    authorizeUrl: string;
};

export type GoogleOauthStatusResponse = {
    connected: boolean;
    channelId: (string) | null;
    channelTitle: (string) | null;
    needsReauth: boolean;
};

export type ImageDescription = {
    description: (string) | null;
};

export type ImageDescriptionInput = {
    imageUrl: string;
};

export type LinkPreview = {
    url: string;
    meta?: {
        title?: string;
        description?: string;
        author?: string;
        site?: string;
    };
    html?: string;
    thumbnail_url?: string;
    provider_name?: string;
    provider_url?: string;
    error?: string;
};

export type LivestreamResponse = {
    mediaItem?: unknown;
    streamKey: string;
    rtmpUrl: string;
    playbackPolicy: 'public' | 'signed';
    muxLiveStreamId: string;
    muxPlaybackId: string;
    liveStatus?: 'idle' | 'active' | 'disabled';
};

export type playbackPolicy = 'public' | 'signed';

export type liveStatus = 'idle' | 'active' | 'disabled';

export type LocalizedContent = {
    siteId: string;
    locale: string;
    title?: (string) | null;
    content?: (string) | null;
    shortContent?: (string) | null;
    extraContent?: (string) | null;
    excerpt?: (string) | null;
    metaTitle?: (string) | null;
    metaDescription?: (string) | null;
    keywords?: (string) | null;
    contentJSON?: {
        [key: string]: unknown;
    } | null;
};

export type Location = {
    id: string;
    siteId: string;
};

export type LocationSlim = {
    siteId: string;
    image?: MediaItem;
    address?: (string) | null;
    address2?: (string) | null;
    state?: (string) | null;
    region?: (string) | null;
    city?: (string) | null;
    zipCode?: (string) | null;
    country?: (string) | null;
    externalLink?: (string) | null;
    mapLink?: (string) | null;
    lat?: (number) | null;
    lng?: (number) | null;
    tags?: Array<Tag>;
    localizedContent: Array<LocalizedContent>;
    isDefault?: boolean;
};

export type LocationsListResponse = {
    records: Array<Location>;
    count: number;
};

export type LocationTagsResponse = {
    records: Array<{
        [key: string]: unknown;
    }>;
};

export type MediaCollection = {
    id: string;
    siteId: string;
    name: string;
    description: (string) | null;
    entityType: (string) | null;
    entityId: (string) | null;
    createdAt: string;
    updatedAt: string;
    items?: Array<{
        mediaItemId: string;
        collectionId: string;
        order: number;
        mediaItem?: unknown;
    }>;
    roles?: Array<MediaCollectionRole>;
};

export type MediaCollectionRole = {
    mediaCollectionId: string;
    accessRoleId: string;
    accessRole: {
        id: string;
        name: (string) | null;
    };
};

export type MediaDownload = {
    id: string;
    label: string;
    kind: 'rendition' | 'original';
    ext: string;
    status: 'ready' | 'preparing' | 'errored' | 'unavailable';
    url: (string) | null;
    width?: number;
    height?: number;
    filesize?: number;
};

export type kind = 'rendition' | 'original';

export type status5 = 'ready' | 'preparing' | 'errored' | 'unavailable';

export type MediaDownloads = {
    downloads: Array<MediaDownload>;
};

export type MediaItem = {
    siteId: string;
    uploaded: boolean;
    inline: boolean;
    url?: (string) | null;
    mimeType?: (string) | null;
    size: string;
    width?: (number) | null;
    height?: (number) | null;
    duration?: (number) | null;
    metadata?: {
        [key: string]: unknown;
    } | null;
    title?: (string) | null;
    caption?: (string) | null;
    credit?: (string) | null;
    altText?: (string) | null;
};

export type MediaItemRole = {
    mediaItemId: string;
    accessRoleId: string;
    accessRole: {
        id: string;
        name: (string) | null;
    };
};

export type MediaItemUpload = {
    fileName: string;
    mimeType: string;
    size: number;
};

export type MediaOriginalDownload = {
    original: MediaDownload;
};

export type MembershipSubscriber = {
    id: string;
    siteId: string;
};

export type MembershipTier = {
    id: string;
    siteId: string;
};

export type MetaOauthDisconnectResponse = {
    success: boolean;
};

export type MetaOauthStartResponse = {
    authorizeUrl: string;
};

export type MetaOauthStatusResponse = {
    connected: boolean;
    pageId: (string) | null;
    pageName: (string) | null;
    needsReauth: boolean;
};

export type MfaEnroll = {
    factorId: string;
    qrCode: string;
    secret: string;
    uri: string;
};

export type MfaEnrollInput = {
    friendlyName?: string;
};

export type MfaFactorsList = {
    records: Array<{
        id: string;
        friendlyName: (string) | null;
        factorType: string;
        status: string;
    }>;
    count: number;
};

export type MfaOk = {
    success: boolean;
};

export type MfaUnenrollInput = {
    factorId: string;
};

export type MfaVerifyInput = {
    factorId: string;
    code: string;
};

export type NewsDates = {
    /**
     * Array of unique news dates. Format depends on interval: day (YYYY-MM-DD), month (YYYY-MM), or year (YYYY)
     */
    dates: Array<(string)>;
    /**
     * Array of unique years that have news articles
     */
    years: Array<(number)>;
};

export type Note = {
    id: string;
};

export type Ok = {
    success: boolean;
};

export type Page = {
    id: string;
    order: number;
    slug: string;
    featured: boolean;
    featuredExpiration?: (string | unknown);
    date?: (string | unknown);
    type: 'CONTENT' | 'NEWS' | 'NEWSLIST' | 'EVENTLIST' | 'PROFILELIST' | 'PRODUCTLIST' | 'LINK';
    linkUrl?: (string) | null;
    openInNewTab: boolean;
    parentId?: (string) | null;
    siteId: string;
    image?: MediaItem;
    parent?: {
        id: string;
        siteId: string;
        createdAt: string;
        updatedAt: string;
        recordType: 'SOURCE' | 'PUBLISHED' | 'REVISION';
        revisionId?: (number) | null;
        publishState: 'DRAFT' | 'REQUEST' | 'PUBLISHED' | 'CANCELLED';
        source?: (string) | null;
        publishedId?: (string) | null;
        dirty: boolean;
        order: number;
        visible: boolean;
        slug: string;
        featured: boolean;
        featuredExpiration?: (string) | null;
        date?: (string) | null;
        type: 'CONTENT' | 'NEWS' | 'NEWSLIST' | 'EVENTLIST' | 'PROFILELIST' | 'PRODUCTLIST' | 'LINK';
        linkUrl?: (string) | null;
        openInNewTab: boolean;
        imageId?: (string) | null;
        userId?: (string) | null;
        parentId?: (string) | null;
    };
    fullPath?: (string) | null;
    roles: Array<{
        pageId: string;
        accessRoleId: string;
        accessRole: {
            id: string;
            siteId: string;
            createdAt: string;
            updatedAt: string;
            name: string;
            description?: (string) | null;
        };
    }>;
    custom?: Array<CustomSchemaData>;
    tags?: Array<Tag>;
    localizedContent: Array<LocalizedContent>;
    artists?: Array<{
        profile: ProfileSlim;
    }>;
};

export type recordType = 'SOURCE' | 'PUBLISHED' | 'REVISION';

export type PageMediaItemUpload = {
    fileName: string;
    mimeType: string;
    size: number;
};

export type PagesListResponse = {
    records: Array<(Page & {
    id: string;
    siteId: string;
})>;
    count: number;
};

export type PageTagsResponse = {
    records: Array<{
        [key: string]: unknown;
    }>;
};

export type Pagination = {
    page: number;
    limit: number;
    total: number;
    totalPages: number;
};

export type PlaybackToken = {
    token: (string) | null;
};

export type Product = {
    siteId: string;
    slug: string;
    order: number;
    featured: boolean;
    featuredExpiration?: (string | unknown);
    author?: (string) | null;
    tags?: Array<Tag>;
    image?: MediaItem;
    localizedContent: Array<LocalizedContent>;
    artists: Array<{
        profile: ProfileSlim;
    }>;
    variants?: Array<ProductVariant>;
    custom?: Array<CustomSchemaData>;
};

export type ProductMediaItemUpload = {
    fileName: string;
    mimeType: string;
    size: number;
    isMainImage?: boolean;
    contentHash?: string;
    metadata?: {
        width: number;
        height: number;
    };
};

export type ProductsListResponse = {
    records: Array<(Product & {
    id: string;
    siteId: string;
})>;
    count: number;
};

export type ProductTagsResponse = {
    records: Array<{
        [key: string]: unknown;
    }>;
};

export type ProductVariant = {
    id: string;
    siteId: string;
    order: number;
    price: number;
    currency?: (string) | null;
    quantity: number;
    externalLink?: (string) | null;
    catalogID?: (string) | null;
    publicationDate?: (string | unknown);
    productTypeId?: (string) | null;
    productId?: (string) | null;
    image?: (MediaItem & unknown);
    productType?: {
        id: string;
        type: string;
    } | null;
};

export type Profile = {
    siteId: string;
    slug: string;
    tags?: Array<Tag>;
    image?: MediaItem;
    localizedContent: Array<LocalizedContent>;
    custom?: Array<CustomSchemaData>;
};

export type ProfileConnectedRecords = {
    records: Array<{
        [key: string]: unknown;
    }>;
};

export type ProfilePreview = {
    siteId: string;
    slug: string;
    tags?: Array<Tag>;
    image?: MediaItem;
    localizedContent: Array<LocalizedContent>;
    custom?: Array<CustomSchemaData>;
};

export type ProfileSlim = {
    siteId: string;
    slug: string;
    tags?: Array<Tag>;
    image?: MediaItem;
    localizedContent: Array<LocalizedContent>;
    custom?: Array<CustomSchemaData>;
};

export type ProfilesListResponse = {
    records: Array<(Profile & {
    id: string;
    siteId: string;
})>;
    count: number;
};

export type ProfileTagsResponse = {
    records: Array<{
        [key: string]: unknown;
    }>;
};

export type PublicLinkPreview = {
    url: string;
    meta?: {
        title?: string;
        description?: string;
        author?: string;
        site?: string;
    };
    html?: string;
    thumbnail_url?: string;
    provider_name?: string;
    provider_url?: string;
    error?: string;
};

export type PublishState = {
    publishState?: unknown;
};

export type PublishStateResponse = {
    publishState: 'DRAFT' | 'REQUEST' | 'PUBLISHED' | 'CANCELLED';
};

export type Recipient = {
    email: string;
    subject?: string;
    variables?: {
        [key: string]: unknown;
    };
    metadata?: {
        [key: string]: unknown;
    };
};

export type RemoveLocationImageInput = {
    isMainImage?: boolean;
};

export type RemovePageImageInput = {
    isMainImage?: boolean;
};

export type RemoveProductImageInput = {
    isMainImage?: boolean;
};

export type ReorderMediaCollectionItemInput = {
    mediaItemId: string;
    upperNeighbor: (string) | null;
};

export type ReorderProductInput = {
    upperNeighbor: (string) | null;
};

export type ReorderVariantInput = {
    variantId: string;
    upperNeighbor?: string;
};

export type RolesListResponse = {
    records: Array<AccessRole>;
    count: number;
};

export type SearchAllSiteResults = {
    records: Array<{
        id: string;
        type: 'event' | 'page' | 'profile' | 'product';
        slug: string;
        siteId: string;
        image?: (MediaItem & unknown);
        localizedContent: Array<{
            locale: string;
            title?: (string) | null;
            shortContent?: (string) | null;
            content?: (string) | null;
        }>;
        startDate?: (string) | null;
        endDate?: (string) | null;
        similarity: number;
    }>;
};

export type SearchSiteResults = {
    events: Array<{
        id: string;
        image?: (MediaItem & unknown);
        localizedContent: Array<{
            locale: string;
            title?: (string) | null;
            shortContent?: (string) | null;
            content?: (string) | null;
        }>;
        siteId: string;
        slug: string;
    }>;
    pages: Array<{
        id: string;
        image?: (MediaItem & unknown);
        localizedContent: Array<{
            locale: string;
            title?: (string) | null;
            shortContent?: (string) | null;
            content?: (string) | null;
        }>;
        siteId: string;
        slug: string;
    }>;
    profiles: Array<{
        id: string;
        image?: (MediaItem & unknown);
        localizedContent: Array<{
            locale: string;
            title?: (string) | null;
            shortContent?: (string) | null;
            content?: (string) | null;
        }>;
        siteId: string;
        slug: string;
    }>;
    products: Array<{
        id: string;
        image?: (MediaItem & unknown);
        localizedContent: Array<{
            locale: string;
            title?: (string) | null;
            shortContent?: (string) | null;
            content?: (string) | null;
        }>;
        siteId: string;
        slug: string;
    }>;
};

export type SetOwnerForProfileInput = {
    userId: string;
};

export type SimulcastTarget = {
    id: string;
    mediaItemId: string;
    label: string;
    rtmpUrl: string;
    ephemeral: boolean;
    muxSimulcastTargetId: (string) | null;
    createdAt: string;
    updatedAt: string;
};

export type SimulcastTargetList = {
    records: Array<SimulcastTarget>;
};

export type Site = {
    id: string;
    name?: (string) | null;
    description?: (string) | null;
    defaultLocale?: (string) | null;
    timeZone?: (string) | null;
    image?: MediaItem;
    settings: SiteSettings;
    webSites?: Array<WebSite>;
};

export type SiteApiKey = {
    id: string;
    name: string;
    keyPrefix: string;
    createdAt: string;
    lastUsedAt: (string) | null;
};

export type SiteApiKeysListResponse = {
    records: Array<SiteApiKey>;
    count: number;
};

export type SiteApiKeySuccess = {
    success: boolean;
};

export type SiteSettings = {
    locale?: {
        default: string;
        supported: Array<(string)>;
    };
    defaults?: {
        currency?: string;
        event?: {
            location?: string;
        };
    };
    publicSite?: {
        baseUrl?: string;
        template?: {
            id?: string;
            config?: {
                [key: string]: unknown;
            };
            schema?: {
                [key: string]: unknown;
            };
        };
    };
};

export type StopLivestreamResponse = {
    mediaItem?: unknown;
    liveStatus: 'idle' | 'active' | 'disabled' | 'completed';
};

export type liveStatus2 = 'idle' | 'active' | 'disabled' | 'completed';

export type StripeConnectDisconnectSuccess = {
    success: boolean;
};

export type Tag = {
    tagId: string;
    tag: {
        id: string;
        siteId: string;
        title: string;
        parentTags?: Array<{
            tagId: string;
            parentTagId: string;
            createdAt: (string);
            parentTag: {
                id: string;
                siteId: string;
                title: string;
            };
        }>;
    };
};

export type TagGraphListResponse = {
    records: Array<{
        [key: string]: unknown;
    }>;
};

export type TagItemResponse = {
    record: (Tag & {
    id: string;
    title: string;
    siteId: string;
});
};

export type TagListItem = {
    id: string;
    siteId: string;
    title: string;
    parentTags?: Array<{
        tagId: string;
        parentTagId: string;
        createdAt: (string);
        parentTag: {
            id: string;
            siteId: string;
            title: string;
        };
    }>;
};

export type TagRelationsResponse = {
    records: {
        [key: string]: unknown;
    };
};

export type TagsListResponse = {
    records: Array<{
        tag: {
            id: string;
            title: string;
            siteId: string;
        };
    }>;
    count: number;
};

export type Ticket = {
    id: string;
    siteId: string;
};

export type TicketOnEvent = {
    name: string;
    price: number;
    externalLink?: (string) | null;
    currency?: (string) | null;
    roles: Array<unknown>;
    localizedContent?: Array<LocalizedContent>;
    order?: number;
};

export type TicketRecordResponse = {
    records: Ticket;
};

export type TicketsListResponse = {
    records: Array<Ticket>;
    count: number;
};

export type TranslatedContent = {
    content?: unknown;
};

export type TranslateInput = {
    id: string;
    from: string;
    to: string;
};

export type TranslateWebsiteInput = {
    from: string;
    to: string;
};

export type Translation = {
    translatedText: (string) | null;
};

export type UnpublishPageInput = {
    publishState?: 'DRAFT' | 'REQUEST' | 'PUBLISHED' | 'CANCELLED';
};

export type UpdateChildTagsInput = {
    childTagIds: Array<(string)>;
};

export type UpdatedMediaItem = {
    id: string;
    title?: (string) | null;
    caption?: (string) | null;
    credit?: (string) | null;
    altText?: (string) | null;
};

export type UpdateDraftBatchInput = {
    name?: string;
    templateKey?: string;
    subject?: string;
    recipients?: Array<Recipient>;
};

export type UpdateEventInput = {
    [key: string]: unknown;
};

export type UpdateEventTagsInput = {
    tags: Array<(string)>;
};

export type UpdateLocationInput = {
    [key: string]: unknown;
};

export type UpdateLocationTagsInput = {
    tags: Array<(string)>;
};

export type UpdateMediaCollectionInput = {
    name?: string;
    description?: (string) | null;
};

export type UpdateMediaItemInput = {
    title?: (string) | null;
    caption?: (string) | null;
    credit?: (string) | null;
    altText?: (string) | null;
    metadata?: {
        [key: string]: unknown;
    } | null;
};

export type UpdateMediaItemOrderInput = {
    entityType: 'event' | 'profile' | 'page' | 'location' | 'product';
    entityId: string;
    mediaItemId: string;
    upperNeighbor: (string) | null;
};

export type UpdateMediaItemOrderResponse = {
    itemIds: Array<(string)>;
};

export type UpdateNoteInput = {
    [key: string]: unknown;
};

export type UpdateNoteOrderInput = {
    upperNeighbor: string;
};

export type UpdatePageInput = {
    [key: string]: unknown;
};

export type UpdatePageOrderInput = {
    parentId: (string) | null;
    upperNeighbor: (string) | null;
};

export type UpdatePageTagsInput = {
    tags: Array<(string)>;
};

export type UpdateParentTagsInput = {
    parentTagIds: Array<(string)>;
};

export type UpdateProductInput = {
    [key: string]: unknown;
};

export type UpdateProductTagsInput = {
    tags: Array<(string)>;
};

export type UpdateProfileInput = {
    [key: string]: unknown;
};

export type UpdateProfileOrderOnPageInput = {
    upperNeighbor: (string) | null;
};

export type UpdateProfileOrderOnProductInput = {
    upperNeighbor: (string) | null;
};

export type UpdateProfileTagsInput = {
    tags: Array<(string)>;
};

export type UpdateSiteInput = {
    [key: string]: unknown;
};

export type UpdateTagInput = {
    title: string;
};

export type UpdateTicketInput = {
    name?: string;
    description?: (string) | null;
    price?: number;
    currency?: (string) | null;
    externalLink?: (string) | null;
    localizedContent?: Array<{
        locale: string;
        title?: (string) | null;
        content?: (string) | null;
    }>;
    roleIds?: Array<(string)>;
};

export type UpdateUserInput = {
    name?: string;
};

export type UpdateUserOnProfileInput = {
    permission: string;
};

export type UpdateVariantInput = {
    [key: string]: unknown;
};

export type UpdateWebsiteInput = {
    [key: string]: unknown;
};

export type User = {
    id: string;
    siteId: string;
};

export type UsersListResponse = {
    records: Array<User>;
    count: number;
};

export type WebSite = {
    id: string;
    siteId: string;
    customDomain?: (string) | null;
    customSchemaId?: (string) | null;
    config?: {
        [key: string]: unknown;
    } | null;
    image?: (MediaItem & unknown);
    localizedContent?: Array<LocalizedContent> | null;
};

export type Website = {
    id: string;
};

export type WebsiteTemplatesList = {
    records: Array<{
        id: string;
    }>;
    count: number;
};

export type PublicSignInData = {
    body?: {
        email: string;
        password: string;
        captchaToken?: string;
    };
    path: {
        siteKey: string;
    };
};

export type PublicSignInResponse = ({
    session: {
        access_token: string;
        refresh_token: string;
        expires_in: number;
        token_type: string;
    };
    user: {
        id: string;
        email?: string;
    };
});

export type PublicSignInError = ({
    error: string;
});

export type PublicSignOutData = {
    path: {
        siteKey: string;
    };
};

export type PublicSignOutResponse = ({
    success: boolean;
});

export type PublicSignOutError = unknown;

export type PublicSignUpData = {
    body?: {
        email: string;
        password: string;
        captchaToken?: string;
    };
    path: {
        siteKey: string;
    };
};

export type PublicSignUpResponse = ({
    user: {
        id: string;
        email?: string;
    };
    confirmEmail: boolean;
});

export type PublicSignUpError = ({
    error: string;
});

export type GetSiteData = {
    path: {
        siteKey: string;
    };
};

export type GetSiteResponse = (Site);

export type GetSiteError = (unknown);

export type GetEventsData = {
    path: {
        siteKey: string;
    };
    query?: {
        dir?: 'asc' | 'desc';
        featured?: (string | Array<(string)>);
        gt?: (number) | null;
        legacyId?: string;
        limit?: (number) | null;
        lt?: (number) | null;
        orderBy?: string;
        page?: (number) | null;
        query?: (string) | null;
        rootOnly?: (string | Array<(string)>);
        tags?: (string | Array<(string)>);
        upcoming?: (string | Array<(string)>);
    };
};

export type GetEventsResponse = ({
    records: Array<Event>;
    count: number;
});

export type GetEventsError = unknown;

export type GetEventDatesData = {
    path: {
        siteKey: string;
    };
    query?: {
        gt?: (number) | null;
        interval?: 'day' | 'month' | 'year';
        lt?: (number) | null;
        upcoming?: (string | Array<(string)>);
    };
};

export type GetEventDatesResponse = (EventDates);

export type GetEventDatesError = unknown;

export type GetEventData = {
    path: {
        siteKey: string;
        slug: string;
    };
};

export type GetEventResponse = (Event);

export type GetEventError = (unknown);

export type GetNewsData = {
    path: {
        siteKey: string;
    };
    query?: {
        dir?: 'asc' | 'desc';
        featured?: (string | Array<(string)>);
        gt?: (number) | null;
        limit?: (number) | null;
        lt?: (number) | null;
        orderBy?: string;
        page?: (number) | null;
        query?: (string) | null;
        tags?: (string | Array<(string)>);
        upcoming?: (string | Array<(string)>);
    };
};

export type GetNewsResponse = ({
    records: Array<(Page & {
    parent?: {
        [key: string]: unknown;
    };
})>;
    count: number;
});

export type GetNewsError = unknown;

export type GetNewsDatesData = {
    path: {
        siteKey: string;
    };
    query?: {
        gt?: (number) | null;
        interval?: 'day' | 'month' | 'year';
        lt?: (number) | null;
    };
};

export type GetNewsDatesResponse = (NewsDates);

export type GetNewsDatesError = unknown;

export type GetNewsArticleData = {
    path: {
        siteKey: string;
        slug: string;
    };
};

export type GetNewsArticleResponse = ((Page & {
    parent?: {
        [key: string]: unknown;
    };
}));

export type GetNewsArticleError = (unknown);

export type GetPagesData = {
    path: {
        siteKey: string;
    };
    query?: {
        dir?: 'asc' | 'desc';
        featured?: (string | Array<(string)>);
        limit?: (number) | null;
        orderBy?: string;
        page?: (number) | null;
        query?: (string) | null;
        tags?: (string | Array<(string)>);
    };
};

export type GetPagesResponse = ({
    records: Array<(Page & {
    parent?: {
        [key: string]: unknown;
    };
})>;
    count: number;
});

export type GetPagesError = unknown;

export type GetPageData = {
    path: {
        siteKey: string;
        slug: string;
    };
};

export type GetPageResponse = ((Page & {
    parent?: {
        [key: string]: unknown;
    };
}));

export type GetPageError = (unknown);

export type GetProfilesData = {
    path: {
        siteKey: string;
    };
    query?: {
        dir?: 'asc' | 'desc';
        limit?: (number) | null;
        orderBy?: string;
        page?: (number) | null;
        query?: (string) | null;
        tags?: (string | Array<(string)>);
        type?: 'member';
    };
};

export type GetProfilesResponse = ({
    records: Array<Profile>;
    count?: number;
});

export type GetProfilesError = unknown;

export type GetProfileData = {
    path: {
        siteKey: string;
        slug: string;
    };
};

export type GetProfileResponse = (Profile);

export type GetProfileError = (unknown);

export type GetProfileEventsData = {
    path: {
        siteKey: string;
        slug: string;
    };
    query?: {
        dir?: 'asc' | 'desc';
        featured?: (string | Array<(string)>);
        gt?: (number) | null;
        legacyId?: string;
        limit?: (number) | null;
        lt?: (number) | null;
        orderBy?: string;
        page?: (number) | null;
        query?: (string) | null;
        rootOnly?: (string | Array<(string)>);
        tags?: (string | Array<(string)>);
        upcoming?: (string | Array<(string)>);
    };
};

export type GetProfileEventsResponse = ({
    records: Array<Event>;
    count?: number;
});

export type GetProfileEventsError = (unknown);

export type GetProfileProductsData = {
    path: {
        siteKey: string;
        slug: string;
    };
    query?: {
        dir?: 'asc' | 'desc';
        featured?: 'true' | 'false';
        limit?: (number) | null;
        orderBy?: string;
        page?: (number) | null;
    };
};

export type GetProfileProductsResponse = ({
    records: Array<Product>;
    count: number;
});

export type GetProfileProductsError = (unknown);

export type GetProductsData = {
    path: {
        siteKey: string;
    };
    query?: {
        dir?: 'asc' | 'desc';
        limit?: (number) | null;
        orderBy?: string;
        page?: (number) | null;
        query?: (string) | null;
        tags?: (string | Array<(string)>);
        type?: 'member';
    };
};

export type GetProductsResponse = ({
    records: Array<Product>;
    count?: number;
});

export type GetProductsError = unknown;

export type GetProductData = {
    path: {
        siteKey: string;
        slug: string;
    };
};

export type GetProductResponse = (Product);

export type GetProductError = (unknown);

export type SearchSiteData = {
    path: {
        siteKey: string;
    };
    query?: {
        debug?: 'true' | 'false' | '1' | '0';
        dir?: 'asc' | 'desc';
        disableVector?: 'true' | 'false' | '1' | '0';
        limit?: (number) | null;
        minResultSimilarity?: (number) | null;
        noCache?: 'true' | 'false' | '1' | '0';
        orderBy?: string;
        page?: (number) | null;
        query?: (string) | null;
        searchProvider?: ('algolia' | 'trigram' | 'hybrid') | null;
        trigramThreshold?: (number) | null;
        vectorThreshold?: (number) | null;
    };
};

export type SearchSiteResponse = (SearchSiteResults);

export type SearchSiteError = (unknown);

export type SearchAllData = {
    path: {
        siteKey: string;
    };
    query?: {
        debug?: 'true' | 'false' | '1' | '0';
        dir?: 'asc' | 'desc';
        disableVector?: 'true' | 'false' | '1' | '0';
        limit?: (number) | null;
        minResultSimilarity?: (number) | null;
        noCache?: 'true' | 'false' | '1' | '0';
        orderBy?: string;
        page?: (number) | null;
        query?: (string) | null;
        searchProvider?: ('algolia' | 'trigram' | 'hybrid') | null;
        trigramThreshold?: (number) | null;
        vectorThreshold?: (number) | null;
    };
};

export type SearchAllResponse = (SearchAllSiteResults);

export type SearchAllError = (unknown);

export type GetTagsData = {
    path: {
        siteKey: string;
    };
    query?: {
        dir?: 'asc' | 'desc';
        limit?: (number) | null;
        orderBy?: string;
        page?: (number) | null;
        parentId?: string;
        query?: string;
    };
};

export type GetTagsResponse = ({
    records: Array<TagListItem>;
    count?: number;
});

export type GetTagsError = unknown;

export type GetPublicLinkPreviewData = {
    path: {
        siteKey: string;
    };
    query: {
        url: string;
    };
};

export type GetPublicLinkPreviewResponse = (PublicLinkPreview);

export type GetPublicLinkPreviewError = (unknown);

export type GetPlaybackTokenData = {
    path: {
        mediaItemId: string;
        siteKey: string;
    };
};

export type GetPlaybackTokenResponse = (PlaybackToken);

export type GetPlaybackTokenError = (unknown);

export type ListSiteDomainsData = {
    path: {
        siteKey: string;
    };
};

export type ListSiteDomainsResponse = ({
    records: Array<{
        siteKey: string;
        customDomain: string;
    }>;
});

export type ListSiteDomainsError = unknown;

export type GetSiteByDomainData = {
    path: {
        domain: string;
        siteKey: string;
    };
};

export type GetSiteByDomainResponse = ({
    id: string;
    siteKey: string;
});

export type GetSiteByDomainError = (unknown);

export type GetImageDescriptionData = {
    body?: ImageDescriptionInput;
    path: {
        siteKey: string;
    };
};

export type GetImageDescriptionResponse = (ImageDescription);

export type GetImageDescriptionError = (unknown);

export type TranslateEventData = {
    body?: TranslateInput;
    path: {
        siteKey: string;
    };
};

export type TranslateEventResponse = (Translation);

export type TranslateEventError = (unknown);

export type TranslateProfileData = {
    body?: TranslateInput;
    path: {
        siteKey: string;
    };
};

export type TranslateProfileResponse = (Translation);

export type TranslateProfileError = (unknown);

export type TranslatePageData = {
    body?: TranslateInput;
    path: {
        siteKey: string;
    };
};

export type TranslatePageResponse = (Translation);

export type TranslatePageError = (unknown);

export type TranslateLocationData = {
    body?: TranslateInput;
    path: {
        siteKey: string;
    };
};

export type TranslateLocationResponse = (Translation);

export type TranslateLocationError = (unknown);

export type TranslateProductData = {
    body?: TranslateInput;
    path: {
        siteKey: string;
    };
};

export type TranslateProductResponse = (Translation);

export type TranslateProductError = (unknown);

export type ListSiteApiKeysData = {
    path: {
        siteKey: string;
    };
};

export type ListSiteApiKeysResponse = (SiteApiKeysListResponse);

export type ListSiteApiKeysError = (unknown);

export type CreateSiteApiKeyData = {
    body?: CreateSiteApiKeyInput;
    path: {
        siteKey: string;
    };
};

export type CreateSiteApiKeyResponse2 = (CreateSiteApiKeyResponse);

export type CreateSiteApiKeyError = (unknown);

export type RevokeSiteApiKeyData = {
    path: {
        keyId: string;
        siteKey: string;
    };
};

export type RevokeSiteApiKeyResponse = (SiteApiKeySuccess);

export type RevokeSiteApiKeyError = (unknown);

export type GetEmailConfigData = {
    path: {
        siteKey: string;
    };
};

export type GetEmailConfigResponse = (EmailConfig);

export type GetEmailConfigError = (unknown);

export type UpdateEmailConfigData = {
    body?: EmailConfigInput;
    path: {
        siteKey: string;
    };
};

export type UpdateEmailConfigResponse = (EmailConfig);

export type UpdateEmailConfigError = (unknown);

export type GetDomainStatusData = {
    path: {
        siteKey: string;
    };
};

export type GetDomainStatusResponse = (DomainStatus);

export type GetDomainStatusError = (unknown);

export type AddCustomDomainData = {
    body?: AddDomainInput;
    path: {
        siteKey: string;
    };
};

export type AddCustomDomainResponse = (AddDomainResponse);

export type AddCustomDomainError = (unknown);

export type RemoveCustomDomainData = {
    path: {
        siteKey: string;
    };
};

export type RemoveCustomDomainResponse = ({
    success: boolean;
});

export type RemoveCustomDomainError = (unknown);

export type VerifyDomainData = {
    path: {
        siteKey: string;
    };
};

export type VerifyDomainResponse = (DomainStatus);

export type VerifyDomainError = (unknown);

export type GetEmailsData = {
    path: {
        siteKey: string;
    };
    query?: {
        batchId?: string;
        endDate?: string;
        limit?: string;
        page?: string;
        startDate?: string;
        status?: 'PENDING' | 'SENT' | 'DELIVERED' | 'BOUNCED' | 'FAILED';
        templateKey?: string;
    };
};

export type GetEmailsResponse = (EmailsResponse);

export type GetEmailsError = (unknown);

export type GetEmailStatsData = {
    path: {
        siteKey: string;
    };
    query?: {
        days?: string;
    };
};

export type GetEmailStatsResponse = (EmailStats);

export type GetEmailStatsError = (unknown);

export type GetEmailByIdData = {
    path: {
        emailId: string;
        siteKey: string;
    };
};

export type GetEmailByIdResponse = (Email);

export type GetEmailByIdError = (unknown);

export type GetEmailBatchesData = {
    path: {
        siteKey: string;
    };
    query?: {
        endDate?: string;
        limit?: string;
        page?: string;
        startDate?: string;
        status?: 'DRAFT' | 'SENDING' | 'COMPLETED';
        templateKey?: string;
    };
};

export type GetEmailBatchesResponse = (EmailBatchesResponse);

export type GetEmailBatchesError = (unknown);

export type CreateDraftBatchData = {
    body?: CreateDraftBatchInput;
    path: {
        siteKey: string;
    };
};

export type CreateDraftBatchResponse = (DraftBatchResult);

export type CreateDraftBatchError = (unknown);

export type GetEmailBatchData = {
    path: {
        batchId: string;
        siteKey: string;
    };
};

export type GetEmailBatchResponse = (EmailBatchDetail);

export type GetEmailBatchError = (unknown);

export type UpdateDraftBatchData = {
    body?: UpdateDraftBatchInput;
    path: {
        batchId: string;
        siteKey: string;
    };
};

export type UpdateDraftBatchResponse = ({
    updated: boolean;
});

export type UpdateDraftBatchError = (unknown);

export type DeleteBatchData = {
    path: {
        batchId: string;
        siteKey: string;
    };
};

export type DeleteBatchResponse = ({
    deleted: boolean;
});

export type DeleteBatchError = (unknown);

export type CreateAndSendBatchData = {
    body?: CreateDraftBatchInput;
    path: {
        siteKey: string;
    };
};

export type CreateAndSendBatchResponse = (BatchSendResult);

export type CreateAndSendBatchError = (unknown);

export type SendBatchData = {
    path: {
        batchId: string;
        siteKey: string;
    };
};

export type SendBatchResponse = (BatchSendResult);

export type SendBatchError = (unknown);

export type UpdateMediaItemOrderData = {
    body?: UpdateMediaItemOrderInput;
    path: {
        siteKey: string;
    };
};

export type UpdateMediaItemOrderResponse2 = (UpdateMediaItemOrderResponse);

export type UpdateMediaItemOrderError = (unknown);

export type DetachMediaItemFromEntityData = {
    body?: DetachMediaItemInput;
    path: {
        siteKey: string;
    };
};

export type DetachMediaItemFromEntityResponse = (DetachMediaItemResponse);

export type DetachMediaItemFromEntityError = (unknown);

export type ListMediaItemDownloadsData = {
    path: {
        mediaItemId: string;
        siteKey: string;
    };
};

export type ListMediaItemDownloadsResponse = (MediaDownloads);

export type ListMediaItemDownloadsError = (unknown);

export type RequestMediaItemOriginalDownloadData = {
    path: {
        mediaItemId: string;
        siteKey: string;
    };
};

export type RequestMediaItemOriginalDownloadResponse = (MediaOriginalDownload);

export type RequestMediaItemOriginalDownloadError = (unknown);

export type ListMediaItemRolesData = {
    path: {
        mediaItemId: string;
        siteKey: string;
    };
};

export type ListMediaItemRolesResponse = (Array<MediaItemRole>);

export type ListMediaItemRolesError = (unknown);

export type AddRoleToMediaItemData = {
    body?: AddRoleToMediaItemInput;
    path: {
        mediaItemId: string;
        siteKey: string;
    };
};

export type AddRoleToMediaItemResponse = (Array<MediaItemRole>);

export type AddRoleToMediaItemError = (unknown);

export type RemoveRoleFromMediaItemData = {
    path: {
        mediaItemId: string;
        roleId: string;
        siteKey: string;
    };
};

export type RemoveRoleFromMediaItemResponse = (Array<MediaItemRole>);

export type RemoveRoleFromMediaItemError = (unknown);

export type UpdateMediaItemData = {
    body?: UpdateMediaItemInput;
    path: {
        mediaItemId: string;
        siteKey: string;
    };
};

export type UpdateMediaItemResponse = (UpdatedMediaItem);

export type UpdateMediaItemError = (unknown);

export type DeleteMediaItemData = {
    path: {
        mediaItemId: string;
        siteKey: string;
    };
};

export type DeleteMediaItemResponse = ({
    success: boolean;
});

export type DeleteMediaItemError = (unknown);

export type ListMfaFactorsData = {
    path: {
        siteKey: string;
    };
};

export type ListMfaFactorsResponse = (MfaFactorsList);

export type ListMfaFactorsError = (unknown);

export type EnrollMfaFactorData = {
    body?: MfaEnrollInput;
    path: {
        siteKey: string;
    };
};

export type EnrollMfaFactorResponse = (MfaEnroll);

export type EnrollMfaFactorError = (unknown);

export type VerifyMfaFactorData = {
    body?: MfaVerifyInput;
    path: {
        siteKey: string;
    };
};

export type VerifyMfaFactorResponse = (MfaOk);

export type VerifyMfaFactorError = (unknown);

export type UnenrollMfaFactorData = {
    body?: MfaUnenrollInput;
    path: {
        siteKey: string;
    };
};

export type UnenrollMfaFactorResponse = (MfaOk);

export type UnenrollMfaFactorError = (unknown);

export type ListMediaCollectionsData = {
    path: {
        siteKey: string;
    };
    query?: {
        entityId?: string;
        entityType?: 'event' | 'profile' | 'page' | 'location' | 'product';
    };
};

export type ListMediaCollectionsResponse = (Array<MediaCollection>);

export type ListMediaCollectionsError = unknown;

export type CreateMediaCollectionData = {
    body?: CreateMediaCollectionInput;
    path: {
        siteKey: string;
    };
};

export type CreateMediaCollectionResponse = (MediaCollection);

export type CreateMediaCollectionError = (unknown);

export type GetMediaCollectionData = {
    path: {
        collectionId: string;
        siteKey: string;
    };
};

export type GetMediaCollectionResponse = (MediaCollection);

export type GetMediaCollectionError = (unknown);

export type UpdateMediaCollectionData = {
    body?: UpdateMediaCollectionInput;
    path: {
        collectionId: string;
        siteKey: string;
    };
};

export type UpdateMediaCollectionResponse = (MediaCollection);

export type UpdateMediaCollectionError = (unknown);

export type DeleteMediaCollectionData = {
    path: {
        collectionId: string;
        siteKey: string;
    };
};

export type DeleteMediaCollectionResponse = ({
    ok: boolean;
});

export type DeleteMediaCollectionError = (unknown);

export type AddItemToMediaCollectionData = {
    body?: AddMediaItemToCollectionInput;
    path: {
        collectionId: string;
        siteKey: string;
    };
};

export type AddItemToMediaCollectionResponse = (MediaCollection);

export type AddItemToMediaCollectionError = (unknown);

export type ReorderMediaCollectionItemData = {
    body?: ReorderMediaCollectionItemInput;
    path: {
        collectionId: string;
        siteKey: string;
    };
};

export type ReorderMediaCollectionItemResponse = (MediaCollection);

export type ReorderMediaCollectionItemError = (unknown);

export type RemoveItemFromMediaCollectionData = {
    path: {
        collectionId: string;
        mediaItemId: string;
        siteKey: string;
    };
    query?: {
        ensureEntityId?: string;
        ensureEntityType?: 'event' | 'profile' | 'page' | 'location' | 'product';
    };
};

export type RemoveItemFromMediaCollectionResponse = (MediaCollection);

export type RemoveItemFromMediaCollectionError = (unknown);

export type ListMediaCollectionRolesData = {
    path: {
        collectionId: string;
        siteKey: string;
    };
};

export type ListMediaCollectionRolesResponse = (Array<MediaCollectionRole>);

export type ListMediaCollectionRolesError = (unknown);

export type AddRoleToMediaCollectionData = {
    body?: AddRoleToMediaCollectionInput;
    path: {
        collectionId: string;
        siteKey: string;
    };
};

export type AddRoleToMediaCollectionResponse = (Array<MediaCollectionRole>);

export type AddRoleToMediaCollectionError = (unknown);

export type RemoveRoleFromMediaCollectionData = {
    path: {
        collectionId: string;
        roleId: string;
        siteKey: string;
    };
};

export type RemoveRoleFromMediaCollectionResponse = (Array<MediaCollectionRole>);

export type RemoveRoleFromMediaCollectionError = (unknown);

export type GetEntityMediaCountData = {
    path: {
        entityId: string;
        entityType: 'event' | 'profile' | 'page' | 'location' | 'product';
        siteKey: string;
    };
};

export type GetEntityMediaCountResponse = (EntityMediaCount);

export type GetEntityMediaCountError = (unknown);

export type ListEntityMediaItemsData = {
    path: {
        entityId: string;
        entityType: 'event' | 'profile' | 'page' | 'location' | 'product';
        siteKey: string;
    };
};

export type ListEntityMediaItemsResponse = (EntityMediaItems);

export type ListEntityMediaItemsError = (unknown);

export type GetNewsPublicPreviewData = {
    path: {
        siteKey: string;
    };
    query?: {
        dir?: 'asc' | 'desc';
        featured?: (string | Array<(string)>);
        gt?: (number) | null;
        limit?: (number) | null;
        lt?: (number) | null;
        orderBy?: string;
        page?: (number) | null;
        query?: (string) | null;
        tags?: (string | Array<(string)>);
        upcoming?: (string | Array<(string)>);
    };
};

export type GetNewsPublicPreviewResponse = ({
    records: Array<(Page & {
    parent?: {
        [key: string]: unknown;
    };
})>;
    count: number;
});

export type GetNewsPublicPreviewError = (unknown);

export type AddImageToNoteData = {
    body?: AddImageToNoteInput;
    path: {
        noteId: string;
        siteKey: string;
    };
};

export type AddImageToNoteResponse2 = (AddImageToNoteResponse);

export type AddImageToNoteError = (unknown);

export type ListPagesData = {
    path: {
        siteKey: string;
    };
    query?: {
        dir?: 'asc' | 'desc';
        limit?: (number) | null;
        orderBy?: string;
        page?: (number) | null;
        publishState?: 'DRAFT' | 'REQUEST' | 'PUBLISHED' | 'CANCELLED';
        query?: string;
        type?: 'CONTENT' | 'NEWS' | 'NEWSLIST' | 'EVENTLIST' | 'PROFILELIST' | 'PRODUCTLIST' | 'LINK';
    };
};

export type ListPagesResponse = (PagesListResponse);

export type ListPagesError = (unknown);

export type CreatePageData = {
    body?: CreatePageInput;
    path: {
        siteKey: string;
    };
};

export type CreatePageResponse = ((Page & {
    id: string;
    siteId: string;
}));

export type CreatePageError = (unknown);

export type GetPagesPublicPreviewData = {
    path: {
        siteKey: string;
    };
    query?: {
        dir?: 'asc' | 'desc';
        featured?: (string | Array<(string)>);
        limit?: (number) | null;
        orderBy?: string;
        page?: (number) | null;
        query?: (string) | null;
        tags?: (string | Array<(string)>);
    };
};

export type GetPagesPublicPreviewResponse = ({
    records: Array<(Page & {
    parent?: {
        [key: string]: unknown;
    };
})>;
    count: number;
});

export type GetPagesPublicPreviewError = (unknown);

export type GetPage1Data = {
    path: {
        pageId: string;
        siteKey: string;
    };
};

export type GetPage1Response = ((Page & {
    id: string;
    siteId: string;
}));

export type GetPage1Error = (unknown);

export type DeletePageData = {
    path: {
        pageId: string;
        siteKey: string;
    };
};

export type DeletePageResponse = (DeleteResponse);

export type DeletePageError = (unknown);

export type UpdatePageData = {
    body?: UpdatePageInput;
    path: {
        pageId: string;
        siteKey: string;
    };
};

export type UpdatePageResponse = ((Page & {
    id: string;
    siteId: string;
}));

export type UpdatePageError = (unknown);

export type PublishPageData = {
    path: {
        pageId: string;
        siteKey: string;
    };
};

export type PublishPageResponse = (PublishStateResponse);

export type PublishPageError = (unknown);

export type UnpublishPageData = {
    body?: UnpublishPageInput;
    path: {
        pageId: string;
        siteKey: string;
    };
};

export type UnpublishPageResponse = ((Page & {
    id: string;
    siteId: string;
}));

export type UnpublishPageError = (unknown);

export type AddLocaleToPageData = {
    body?: AddLocaleToPageInput;
    path: {
        pageId: string;
        siteKey: string;
    };
};

export type AddLocaleToPageResponse = ((Page & {
    id: string;
    siteId: string;
}));

export type AddLocaleToPageError = (unknown);

export type AddRoleToPageData = {
    body?: AddRoleToPageInput;
    path: {
        pageId: string;
        siteKey: string;
    };
};

export type AddRoleToPageResponse = ((Page & {
    id: string;
    siteId: string;
}));

export type AddRoleToPageError = (unknown);

export type RemoveRoleFromPageData = {
    path: {
        pageId: string;
        roleId: string;
        siteKey: string;
    };
};

export type RemoveRoleFromPageResponse = (DeleteResponse);

export type RemoveRoleFromPageError = (unknown);

export type AddParentToPageData = {
    body?: AddParentToPageInput;
    path: {
        pageId: string;
        siteKey: string;
    };
};

export type AddParentToPageResponse = ((Page & {
    id: string;
    siteId: string;
}));

export type AddParentToPageError = (unknown);

export type UpdatePageOrderData = {
    body?: UpdatePageOrderInput;
    path: {
        pageId: string;
        siteKey: string;
    };
};

export type UpdatePageOrderResponse = (unknown);

export type UpdatePageOrderError = (unknown);

export type AddProfileToPageData = {
    body?: AddProfileToPageInput;
    path: {
        pageId: string;
        siteKey: string;
    };
};

export type AddProfileToPageResponse = ((Page & {
    id: string;
    siteId: string;
}));

export type AddProfileToPageError = (unknown);

export type RemoveProfileFromPageData = {
    path: {
        pageId: string;
        profileId: string;
        siteKey: string;
    };
};

export type RemoveProfileFromPageResponse = (DeleteResponse);

export type RemoveProfileFromPageError = (unknown);

export type ToggleProfileVisibilityOnPageData = {
    path: {
        pageId: string;
        profileId: string;
        siteKey: string;
    };
};

export type ToggleProfileVisibilityOnPageResponse = ((Page & {
    id: string;
    siteId: string;
}));

export type ToggleProfileVisibilityOnPageError = (unknown);

export type UpdateProfileOrderOnPageData = {
    body?: UpdateProfileOrderOnPageInput;
    path: {
        pageId: string;
        profileId: string;
        siteKey: string;
    };
};

export type UpdateProfileOrderOnPageResponse = (unknown);

export type UpdateProfileOrderOnPageError = (unknown);

export type AddImageToPageData = {
    body?: PageMediaItemUpload;
    path: {
        pageId: string;
        siteKey: string;
    };
};

export type AddImageToPageResponse = (AddPageImageResponse);

export type AddImageToPageError = (unknown);

export type RemoveImageFromPageData = {
    body?: RemovePageImageInput;
    path: {
        pageId: string;
        siteKey: string;
    };
};

export type RemoveImageFromPageResponse = (DeleteResponse);

export type RemoveImageFromPageError = (unknown);

export type BustPageCacheData = {
    path: {
        pageId: string;
        siteKey: string;
    };
};

export type BustPageCacheResponse = (BustCacheResponse);

export type BustPageCacheError = (unknown);

export type ListPageTagsData = {
    path: {
        pageId: string;
        siteKey: string;
    };
};

export type ListPageTagsResponse = (PageTagsResponse);

export type ListPageTagsError = (unknown);

export type UpdatePageTagsData = {
    body?: UpdatePageTagsInput;
    path: {
        pageId: string;
        siteKey: string;
    };
};

export type UpdatePageTagsResponse = (PageTagsResponse);

export type UpdatePageTagsError = (unknown);

export type CreateProfileData = {
    body?: CreateProfileInput;
    path: {
        siteKey: string;
    };
};

export type CreateProfileResponse = ((Profile & {
    id: string;
    siteId: string;
}));

export type CreateProfileError = (unknown);

export type ListProfilesData = {
    path: {
        siteKey: string;
    };
    query?: {
        dir?: 'asc' | 'desc';
        limit?: (number) | null;
        orderBy?: string;
        page?: (number) | null;
        query?: string;
    };
};

export type ListProfilesResponse = (ProfilesListResponse);

export type ListProfilesError = (unknown);

export type GetProfilesPublicPreviewData = {
    path: {
        siteKey: string;
    };
    query?: {
        dir?: 'asc' | 'desc';
        limit?: number;
        orderBy?: 'slug' | 'createdAt' | 'updatedAt';
        page?: (number) | null;
        query?: (string) | null;
        tags?: (string | Array<(string)>);
        type?: 'member';
    };
};

export type GetProfilesPublicPreviewResponse = ({
    records: Array<ProfilePreview>;
    count: number;
});

export type GetProfilesPublicPreviewError = (unknown);

export type GetProfile1Data = {
    path: {
        profileId: string;
        siteKey: string;
    };
};

export type GetProfile1Response = ((Profile & {
    id: string;
    siteId: string;
}));

export type GetProfile1Error = (unknown);

export type UpdateProfileData = {
    body?: UpdateProfileInput;
    path: {
        profileId: string;
        siteKey: string;
    };
};

export type UpdateProfileResponse = ((Profile & {
    id: string;
    siteId: string;
}));

export type UpdateProfileError = (unknown);

export type RemoveProfileData = {
    path: {
        profileId: string;
        siteKey: string;
    };
};

export type RemoveProfileResponse = (Ok);

export type RemoveProfileError = (unknown);

export type GetProfileEvents1Data = {
    path: {
        profileId: string;
        siteKey: string;
    };
};

export type GetProfileEvents1Response = (ProfileConnectedRecords);

export type GetProfileEvents1Error = (unknown);

export type GetProfileProducts1Data = {
    path: {
        profileId: string;
        siteKey: string;
    };
};

export type GetProfileProducts1Response = (ProfileConnectedRecords);

export type GetProfileProducts1Error = (unknown);

export type GetProfilePagesData = {
    path: {
        profileId: string;
        siteKey: string;
    };
};

export type GetProfilePagesResponse = (ProfileConnectedRecords);

export type GetProfilePagesError = (unknown);

export type PublishProfileData = {
    path: {
        profileId: string;
        siteKey: string;
    };
};

export type PublishProfileResponse = (PublishState);

export type PublishProfileError = (unknown);

export type AddImageToProfileData = {
    body?: MediaItemUpload;
    path: {
        profileId: string;
        siteKey: string;
    };
};

export type AddImageToProfileResponse = (AddImageResponse);

export type AddImageToProfileError = (unknown);

export type RemoveImageFromProfileData = {
    body?: MediaItemUpload;
    path: {
        profileId: string;
        siteKey: string;
    };
};

export type RemoveImageFromProfileResponse = (Ok);

export type RemoveImageFromProfileError = (unknown);

export type AddUserToProfileData = {
    body?: AddUserToProfileInput;
    path: {
        profileId: string;
        siteKey: string;
    };
};

export type AddUserToProfileResponse = ((Profile & {
    id: string;
    siteId: string;
}));

export type AddUserToProfileError = (unknown);

export type UpdateUserOnProfileData = {
    body?: UpdateUserOnProfileInput;
    path: {
        profileId: string;
        siteKey: string;
        userId: string;
    };
};

export type UpdateUserOnProfileResponse = ((Profile & {
    id: string;
    siteId: string;
}));

export type UpdateUserOnProfileError = (unknown);

export type RemoveUserFromProfileData = {
    path: {
        profileId: string;
        siteKey: string;
        userId: string;
    };
};

export type RemoveUserFromProfileResponse = ((Profile & {
    id: string;
    siteId: string;
}));

export type RemoveUserFromProfileError = (unknown);

export type SetOwnerForProfileData = {
    body?: SetOwnerForProfileInput;
    path: {
        profileId: string;
        siteKey: string;
    };
};

export type SetOwnerForProfileResponse = ((Profile & {
    id: string;
    siteId: string;
}));

export type SetOwnerForProfileError = (unknown);

export type GetProfileNotesData = {
    path: {
        profileId: string;
        siteKey: string;
    };
};

export type GetProfileNotesResponse = (ProfileConnectedRecords);

export type GetProfileNotesError = (unknown);

export type AddNoteToProfileData = {
    path: {
        profileId: string;
        siteKey: string;
    };
};

export type AddNoteToProfileResponse = (Note);

export type AddNoteToProfileError = (unknown);

export type UpdateNoteOnProfileData = {
    body?: UpdateNoteInput;
    path: {
        noteId: string;
        profileId: string;
        siteKey: string;
    };
};

export type UpdateNoteOnProfileResponse = (Note);

export type UpdateNoteOnProfileError = (unknown);

export type RemoveNoteOnProfileData = {
    path: {
        noteId: string;
        profileId: string;
        siteKey: string;
    };
};

export type RemoveNoteOnProfileResponse = (Ok);

export type RemoveNoteOnProfileError = (unknown);

export type UpdateNoteOrderOnProfileData = {
    body?: UpdateNoteOrderInput;
    path: {
        noteId: string;
        profileId: string;
        siteKey: string;
    };
};

export type UpdateNoteOrderOnProfileResponse = ((Profile & {
    id: string;
    siteId: string;
}));

export type UpdateNoteOrderOnProfileError = (unknown);

export type ListProfileTagsData = {
    path: {
        profileId: string;
        siteKey: string;
    };
};

export type ListProfileTagsResponse = (ProfileTagsResponse);

export type ListProfileTagsError = (unknown);

export type UpdateProfileTagsData = {
    body?: UpdateProfileTagsInput;
    path: {
        profileId: string;
        siteKey: string;
    };
};

export type UpdateProfileTagsResponse = (ProfileTagsResponse);

export type UpdateProfileTagsError = (unknown);

export type ListTagsData = {
    path: {
        siteKey: string;
    };
    query?: {
        limit?: (number) | null;
        page?: (number) | null;
        query?: string;
    };
};

export type ListTagsResponse = (TagsListResponse);

export type ListTagsError = (unknown);

export type CreateTagData = {
    body?: CreateTagInput;
    path: {
        siteKey: string;
    };
};

export type CreateTagResponse = ((Tag & {
    id: string;
    title: string;
    siteId: string;
}));

export type CreateTagError = (unknown);

export type ListParentTagsData = {
    path: {
        siteKey: string;
        tagId: string;
    };
};

export type ListParentTagsResponse = (TagGraphListResponse);

export type ListParentTagsError = (unknown);

export type UpdateParentTagsData = {
    body?: UpdateParentTagsInput;
    path: {
        siteKey: string;
        tagId: string;
    };
};

export type UpdateParentTagsResponse = (TagGraphListResponse);

export type UpdateParentTagsError = (unknown);

export type ListChildTagsData = {
    path: {
        siteKey: string;
        tagId: string;
    };
};

export type ListChildTagsResponse = (TagGraphListResponse);

export type ListChildTagsError = (unknown);

export type UpdateChildTagsData = {
    body?: UpdateChildTagsInput;
    path: {
        siteKey: string;
        tagId: string;
    };
};

export type UpdateChildTagsResponse = (TagGraphListResponse);

export type UpdateChildTagsError = (unknown);

export type ListTagRelationsData = {
    path: {
        siteKey: string;
        tagId: string;
    };
};

export type ListTagRelationsResponse = (TagRelationsResponse);

export type ListTagRelationsError = (unknown);

export type AttachEventToTagData = {
    body?: AttacheventsToTagInput;
    path: {
        siteKey: string;
        tagId: string;
    };
};

export type AttachEventToTagResponse = (AttachTagRelationResponse);

export type AttachEventToTagError = (unknown);

export type AttachProfileToTagData = {
    body?: AttachprofilesToTagInput;
    path: {
        siteKey: string;
        tagId: string;
    };
};

export type AttachProfileToTagResponse = (AttachTagRelationResponse);

export type AttachProfileToTagError = (unknown);

export type AttachProductToTagData = {
    body?: AttachproductsToTagInput;
    path: {
        siteKey: string;
        tagId: string;
    };
};

export type AttachProductToTagResponse = (AttachTagRelationResponse);

export type AttachProductToTagError = (unknown);

export type AttachPageToTagData = {
    body?: AttachpagesToTagInput;
    path: {
        siteKey: string;
        tagId: string;
    };
};

export type AttachPageToTagResponse = (AttachTagRelationResponse);

export type AttachPageToTagError = (unknown);

export type GetTagData = {
    path: {
        siteKey: string;
        tagId: string;
    };
};

export type GetTagResponse = (TagItemResponse);

export type GetTagError = (unknown);

export type UpdateTagData = {
    body?: UpdateTagInput;
    path: {
        siteKey: string;
        tagId: string;
    };
};

export type UpdateTagResponse = (TagItemResponse);

export type UpdateTagError = (unknown);

export type DisconnectStripeConnectData = {
    path: {
        siteKey: string;
    };
};

export type DisconnectStripeConnectResponse = (StripeConnectDisconnectSuccess);

export type DisconnectStripeConnectError = (unknown);

export type ListTicketsData = {
    path: {
        siteKey: string;
    };
    query?: {
        limit?: (number) | null;
        page?: (number) | null;
    };
};

export type ListTicketsResponse = (TicketsListResponse);

export type ListTicketsError = (unknown);

export type CreateTicketData = {
    body?: CreateTicketInput;
    path: {
        siteKey: string;
    };
};

export type CreateTicketResponse = (TicketRecordResponse);

export type CreateTicketError = (unknown);

export type UpdateTicketData = {
    body?: UpdateTicketInput;
    path: {
        siteKey: string;
        ticketId: string;
    };
};

export type UpdateTicketResponse = (TicketRecordResponse);

export type UpdateTicketError = (unknown);

export type DeleteTicketData = {
    path: {
        siteKey: string;
        ticketId: string;
    };
};

export type DeleteTicketResponse = (TicketRecordResponse);

export type DeleteTicketError = (unknown);

export type ListRolesData = {
    path: {
        siteKey: string;
    };
    query?: {
        limit?: (number) | null;
        page?: (number) | null;
    };
};

export type ListRolesResponse = (RolesListResponse);

export type ListRolesError = (unknown);

export type ListLocationsData = {
    path: {
        siteKey: string;
    };
    query?: {
        dir?: 'asc' | 'desc';
        limit?: (number) | null;
        orderBy?: string;
        page?: (number) | null;
        query?: string;
    };
};

export type ListLocationsResponse = (LocationsListResponse);

export type ListLocationsError = (unknown);

export type CreateLocationData = {
    body?: CreateLocationInput;
    path: {
        siteKey: string;
    };
};

export type CreateLocationResponse = (Location);

export type CreateLocationError = (unknown);

export type GetLocationData = {
    path: {
        locationId: string;
        siteKey: string;
    };
};

export type GetLocationResponse = (Location);

export type GetLocationError = (unknown);

export type UpdateLocationData = {
    body?: UpdateLocationInput;
    path: {
        locationId: string;
        siteKey: string;
    };
};

export type UpdateLocationResponse = (Location);

export type UpdateLocationError = (unknown);

export type PublishLocationData = {
    path: {
        locationId: string;
        siteKey: string;
    };
};

export type PublishLocationResponse = (PublishState);

export type PublishLocationError = (unknown);

export type AddImageToLocationData = {
    body?: MediaItemUpload;
    path: {
        locationId: string;
        siteKey: string;
    };
};

export type AddImageToLocationResponse = (AddImageResponse);

export type AddImageToLocationError = (unknown);

export type RemoveImageFromLocationData = {
    body?: RemoveLocationImageInput;
    path: {
        locationId: string;
        siteKey: string;
    };
};

export type RemoveImageFromLocationResponse = (Ok);

export type RemoveImageFromLocationError = (unknown);

export type AddLocaleToLocationData = {
    body?: AddLocaleToLocationInput;
    path: {
        locationId: string;
        siteKey: string;
    };
};

export type AddLocaleToLocationResponse = (Location);

export type AddLocaleToLocationError = (unknown);

export type AddNoteToLocationData = {
    path: {
        locationId: string;
        siteKey: string;
    };
};

export type AddNoteToLocationResponse = (Note);

export type AddNoteToLocationError = (unknown);

export type UpdateNoteOnLocationData = {
    body?: UpdateNoteInput;
    path: {
        locationId: string;
        noteId: string;
        siteKey: string;
    };
};

export type UpdateNoteOnLocationResponse = (Note);

export type UpdateNoteOnLocationError = (unknown);

export type RemoveNoteOnLocationData = {
    path: {
        locationId: string;
        noteId: string;
        siteKey: string;
    };
};

export type RemoveNoteOnLocationResponse = (Ok);

export type RemoveNoteOnLocationError = (unknown);

export type UpdateNoteOrderOnLocationData = {
    body?: (UpdateNoteOrderInput & {
    upperNeighbor?: (string) | null;
});
    path: {
        locationId: string;
        noteId: string;
        siteKey: string;
    };
};

export type UpdateNoteOrderOnLocationResponse = (Ok);

export type UpdateNoteOrderOnLocationError = (unknown);

export type ListLocationTagsData = {
    path: {
        locationId: string;
        siteKey: string;
    };
};

export type ListLocationTagsResponse = (LocationTagsResponse);

export type ListLocationTagsError = (unknown);

export type UpdateLocationTagsData = {
    body?: UpdateLocationTagsInput;
    path: {
        locationId: string;
        siteKey: string;
    };
};

export type UpdateLocationTagsResponse = (LocationTagsResponse);

export type UpdateLocationTagsError = (unknown);

export type ListProductsData = {
    path: {
        siteKey: string;
    };
    query?: {
        dir?: 'asc' | 'desc';
        limit?: (number) | null;
        orderBy?: string;
        page?: (number) | null;
        query?: string;
    };
};

export type ListProductsResponse = (ProductsListResponse);

export type ListProductsError = (unknown);

export type CreateProductData = {
    path: {
        siteKey: string;
    };
};

export type CreateProductResponse = ((Product & {
    id: string;
    siteId: string;
}));

export type CreateProductError = (unknown);

export type UpdateProductOrderData = {
    body?: ReorderProductInput;
    path: {
        productId: string;
        siteKey: string;
    };
};

export type UpdateProductOrderResponse = ({
    order: Array<(string)>;
});

export type UpdateProductOrderError = (unknown);

export type GetProductsPublicPreviewData = {
    path: {
        siteKey: string;
    };
    query?: {
        dir?: 'asc' | 'desc';
        limit?: (number) | null;
        orderBy?: string;
        page?: (number) | null;
        query?: (string) | null;
        tags?: (string | Array<(string)>);
        type?: 'member';
    };
};

export type GetProductsPublicPreviewResponse = ({
    records: Array<Product>;
    count: number;
});

export type GetProductsPublicPreviewError = (unknown);

export type GetProduct1Data = {
    path: {
        productId: string;
        siteKey: string;
    };
};

export type GetProduct1Response = ((Product & {
    id: string;
    siteId: string;
}));

export type GetProduct1Error = (unknown);

export type UpdateProductData = {
    body?: UpdateProductInput;
    path: {
        productId: string;
        siteKey: string;
    };
};

export type UpdateProductResponse = ((Product & {
    id: string;
    siteId: string;
}));

export type UpdateProductError = (unknown);

export type DeleteProductData = {
    path: {
        productId: string;
        siteKey: string;
    };
};

export type DeleteProductResponse = ({
    success: boolean;
});

export type DeleteProductError = (unknown);

export type PublishProductData = {
    path: {
        productId: string;
        siteKey: string;
    };
};

export type PublishProductResponse = ({
    publishState: string;
});

export type PublishProductError = (unknown);

export type AddProductVariantData = {
    path: {
        productId: string;
        siteKey: string;
    };
};

export type AddProductVariantResponse = ((ProductVariant & {
    id: string;
}));

export type AddProductVariantError = (unknown);

export type UpdateVariantOrderOnProductData = {
    body?: ReorderVariantInput;
    path: {
        productId: string;
        siteKey: string;
    };
};

export type UpdateVariantOrderOnProductResponse = ({
    order: Array<(string)>;
});

export type UpdateVariantOrderOnProductError = (unknown);

export type UpdateProductVariantData = {
    body?: UpdateVariantInput;
    path: {
        productId: string;
        siteKey: string;
        variantId: string;
    };
};

export type UpdateProductVariantResponse = ((ProductVariant & {
    id: string;
}));

export type UpdateProductVariantError = (unknown);

export type RemoveProductVariantData = {
    path: {
        productId: string;
        siteKey: string;
        variantId: string;
    };
};

export type RemoveProductVariantResponse = ({
    success: boolean;
});

export type RemoveProductVariantError = (unknown);

export type AddImageToProductData = {
    body?: ProductMediaItemUpload;
    path: {
        productId: string;
        siteKey: string;
    };
};

export type AddImageToProductResponse = (AddProductImageResponse);

export type AddImageToProductError = (unknown);

export type RemoveImageFromProductData = {
    body?: RemoveProductImageInput;
    path: {
        productId: string;
        siteKey: string;
    };
};

export type RemoveImageFromProductResponse = ({
    success: boolean;
});

export type RemoveImageFromProductError = (unknown);

export type AddLocaleToProductData = {
    body?: AddLocaleToProductInput;
    path: {
        productId: string;
        siteKey: string;
    };
};

export type AddLocaleToProductResponse = ((Product & {
    id: string;
    siteId: string;
}));

export type AddLocaleToProductError = (unknown);

export type AddProfileToProductData = {
    body?: AddProfileToProductInput;
    path: {
        productId: string;
        siteKey: string;
    };
};

export type AddProfileToProductResponse = ((Product & {
    id: string;
    siteId: string;
}));

export type AddProfileToProductError = (unknown);

export type RemoveProfileFromProductData = {
    path: {
        productId: string;
        profileId: string;
        siteKey: string;
    };
};

export type RemoveProfileFromProductResponse = ({
    ok: boolean;
});

export type RemoveProfileFromProductError = (unknown);

export type ToggleProfileVisibilityOnProductData = {
    path: {
        productId: string;
        profileId: string;
        siteKey: string;
    };
};

export type ToggleProfileVisibilityOnProductResponse = ((Product & {
    id: string;
    siteId: string;
}));

export type ToggleProfileVisibilityOnProductError = (unknown);

export type UpdateProfileOrderOnProductData = {
    body?: UpdateProfileOrderOnProductInput;
    path: {
        productId: string;
        profileId: string;
        siteKey: string;
    };
};

export type UpdateProfileOrderOnProductResponse = (unknown);

export type UpdateProfileOrderOnProductError = (unknown);

export type ListProductTagsData = {
    path: {
        productId: string;
        siteKey: string;
    };
};

export type ListProductTagsResponse = (ProductTagsResponse);

export type ListProductTagsError = (unknown);

export type UpdateProductTagsData = {
    body?: UpdateProductTagsInput;
    path: {
        productId: string;
        siteKey: string;
    };
};

export type UpdateProductTagsResponse = (ProductTagsResponse);

export type UpdateProductTagsError = (unknown);

export type GetUserData = {
    path: {
        siteKey: string;
        userId: string;
    };
};

export type GetUserResponse = (User);

export type GetUserError = (unknown);

export type UpdateUserData = {
    body?: UpdateUserInput;
    path: {
        siteKey: string;
        userId: string;
    };
};

export type UpdateUserResponse = (User);

export type UpdateUserError = (unknown);

export type ListUsersData = {
    path: {
        siteKey: string;
    };
    query?: {
        dir?: 'asc' | 'desc';
        limit?: (number) | null;
        orderBy?: string;
        page?: (number) | null;
        query?: string;
    };
};

export type ListUsersResponse = (UsersListResponse);

export type ListUsersError = (unknown);

export type CreateUserData = {
    body?: CreateUserInput;
    path: {
        siteKey: string;
    };
};

export type CreateUserResponse = (User);

export type CreateUserError = (unknown);

export type AddImageToUserData = {
    body?: AddImageToUserInput;
    path: {
        siteKey: string;
        userId: string;
    };
};

export type AddImageToUserResponse = (unknown);

export type AddImageToUserError = (unknown);

export type AddRoleToUserData = {
    body?: AddRoleToUserInput;
    path: {
        siteKey: string;
        userId: string;
    };
};

export type AddRoleToUserResponse = (User);

export type AddRoleToUserError = (unknown);

export type RemoveRoleFromUserData = {
    path: {
        roleId: string;
        siteKey: string;
        userId: string;
    };
};

export type RemoveRoleFromUserResponse = ({
    ok: boolean;
});

export type RemoveRoleFromUserError = (unknown);

export type GetBackendLinkPreviewData = {
    path: {
        siteKey: string;
    };
    query: {
        url: string;
    };
};

export type GetBackendLinkPreviewResponse = (LinkPreview);

export type GetBackendLinkPreviewError = (unknown);

export type AtprotoOauthStartData = {
    body?: AtprotoOauthStartInput;
    path: {
        siteKey: string;
    };
};

export type AtprotoOauthStartResponse2 = (AtprotoOauthStartResponse);

export type AtprotoOauthStartError = (unknown);

export type AtprotoOauthDisconnectData = {
    path: {
        siteKey: string;
    };
};

export type AtprotoOauthDisconnectResponse2 = (AtprotoOauthDisconnectResponse);

export type AtprotoOauthDisconnectError = (unknown);

export type AtprotoOauthStatusData = {
    path: {
        siteKey: string;
    };
};

export type AtprotoOauthStatusResponse2 = (AtprotoOauthStatusResponse);

export type AtprotoOauthStatusError = (unknown);

export type AtprotoSettingsGetData = {
    path: {
        siteKey: string;
    };
};

export type AtprotoSettingsGetResponse = (AtprotoSettingsResponse);

export type AtprotoSettingsGetError = (unknown);

export type AtprotoSettingsUpdateData = {
    body?: AtprotoSettingsInput;
    path: {
        siteKey: string;
    };
};

export type AtprotoSettingsUpdateResponse = (AtprotoSettingsResponse);

export type AtprotoSettingsUpdateError = (unknown);

export type MetaOauthStartData = {
    path: {
        siteKey: string;
    };
};

export type MetaOauthStartResponse2 = (MetaOauthStartResponse);

export type MetaOauthStartError = (unknown);

export type MetaOauthDisconnectData = {
    path: {
        siteKey: string;
    };
};

export type MetaOauthDisconnectResponse2 = (MetaOauthDisconnectResponse);

export type MetaOauthDisconnectError = (unknown);

export type MetaOauthStatusData = {
    path: {
        siteKey: string;
    };
};

export type MetaOauthStatusResponse2 = (MetaOauthStatusResponse);

export type MetaOauthStatusError = (unknown);

export type GoogleOauthStartData = {
    path: {
        siteKey: string;
    };
};

export type GoogleOauthStartResponse2 = (GoogleOauthStartResponse);

export type GoogleOauthStartError = (unknown);

export type GoogleOauthDisconnectData = {
    path: {
        siteKey: string;
    };
};

export type GoogleOauthDisconnectResponse2 = (GoogleOauthDisconnectResponse);

export type GoogleOauthDisconnectError = (unknown);

export type GoogleOauthStatusData = {
    path: {
        siteKey: string;
    };
};

export type GoogleOauthStatusResponse2 = (GoogleOauthStatusResponse);

export type GoogleOauthStatusError = (unknown);

export type ListMembershipTiersData = {
    path: {
        siteKey: string;
    };
    query?: {
        limit?: number;
        page?: (number) | null;
    };
};

export type ListMembershipTiersResponse = ({
    records: Array<MembershipTier>;
});

export type ListMembershipTiersError = (unknown);

export type GetMembershipTierData = {
    path: {
        id: string;
        siteKey: string;
    };
};

export type GetMembershipTierResponse = ({
    records: Array<MembershipTier>;
});

export type GetMembershipTierError = (unknown);

export type ListMembershipSubscribersData = {
    path: {
        id: string;
        siteKey: string;
    };
    query?: {
        limit?: number;
        page?: (number) | null;
    };
};

export type ListMembershipSubscribersResponse = ({
    records: Array<MembershipSubscriber>;
    count: number;
});

export type ListMembershipSubscribersError = (unknown);

export type GetSite1Data = {
    path: {
        siteKey: string;
    };
};

export type GetSite1Response = ((Site & {
    id: string;
}));

export type GetSite1Error = (unknown);

export type UpdateSiteData = {
    body?: UpdateSiteInput;
    path: {
        siteKey: string;
    };
};

export type UpdateSiteResponse = ((Site & {
    id: string;
}));

export type UpdateSiteError = (unknown);

export type ListWebsiteTemplatesData = {
    path: {
        siteKey: string;
    };
};

export type ListWebsiteTemplatesResponse = (WebsiteTemplatesList);

export type ListWebsiteTemplatesError = (unknown);

export type RemoveImageFromSiteData = {
    body?: (MediaItemUpload & {
    fileName?: string;
    mimeType?: string;
    size?: number;
    isMainImage?: boolean;
});
    path: {
        siteKey: string;
    };
};

export type RemoveImageFromSiteResponse = (Ok);

export type RemoveImageFromSiteError = (unknown);

export type CreateWebsiteData = {
    path: {
        siteKey: string;
    };
};

export type CreateWebsiteResponse = (Website);

export type CreateWebsiteError = (unknown);

export type UpdateWebsiteData = {
    body?: UpdateWebsiteInput;
    path: {
        siteKey: string;
        websiteId: string;
    };
};

export type UpdateWebsiteResponse = (Website);

export type UpdateWebsiteError = (unknown);

export type AddImageToWebsiteData = {
    body?: (MediaItemUpload & {
    fileName?: string;
    mimeType?: string;
    size?: number;
    isMainImage?: boolean;
});
    path: {
        siteKey: string;
        websiteId: string;
    };
};

export type AddImageToWebsiteResponse = (AddImageResponse);

export type AddImageToWebsiteError = (unknown);

export type RemoveImageFromWebsiteData = {
    body?: (MediaItemUpload & {
    fileName?: string;
    mimeType?: string;
    size?: number;
    isMainImage?: boolean;
});
    path: {
        siteKey: string;
        websiteId: string;
    };
};

export type RemoveImageFromWebsiteResponse = (Ok);

export type RemoveImageFromWebsiteError = (unknown);

export type AddLocaleToWebsiteData = {
    body?: AddLocaleInput;
    path: {
        siteKey: string;
        websiteId: string;
    };
};

export type AddLocaleToWebsiteResponse = (Website);

export type AddLocaleToWebsiteError = (unknown);

export type TranslateWebsiteContentData = {
    body?: TranslateWebsiteInput;
    path: {
        siteKey: string;
        websiteId: string;
    };
};

export type TranslateWebsiteContentResponse = (TranslatedContent);

export type TranslateWebsiteContentError = (unknown);

export type CreateEventLivestreamData = {
    body?: CreateLivestreamInput;
    path: {
        eventId: string;
        siteKey: string;
    };
};

export type CreateEventLivestreamResponse = (LivestreamResponse);

export type CreateEventLivestreamError = (unknown);

export type GetEventLivestreamData = {
    path: {
        mediaItemId: string;
        siteKey: string;
    };
};

export type GetEventLivestreamResponse = (LivestreamResponse);

export type GetEventLivestreamError = (unknown);

export type DeleteEventLivestreamData = {
    path: {
        mediaItemId: string;
        siteKey: string;
    };
};

export type DeleteEventLivestreamResponse = ({
    success: boolean;
});

export type DeleteEventLivestreamError = (unknown);

export type StopEventLivestreamData = {
    path: {
        mediaItemId: string;
        siteKey: string;
    };
};

export type StopEventLivestreamResponse = (StopLivestreamResponse);

export type StopEventLivestreamError = (unknown);

export type ListSimulcastTargetsData = {
    path: {
        mediaItemId: string;
        siteKey: string;
    };
};

export type ListSimulcastTargetsResponse = (SimulcastTargetList);

export type ListSimulcastTargetsError = (unknown);

export type CreateSimulcastTargetData = {
    body?: CreateSimulcastTargetInput;
    path: {
        mediaItemId: string;
        siteKey: string;
    };
};

export type CreateSimulcastTargetResponse = (SimulcastTarget);

export type CreateSimulcastTargetError = (unknown);

export type DeleteSimulcastTargetData = {
    path: {
        mediaItemId: string;
        siteKey: string;
        targetId: string;
    };
};

export type DeleteSimulcastTargetResponse = ({
    success: boolean;
});

export type DeleteSimulcastTargetError = (unknown);

export type ListEventsData = {
    path: {
        siteKey: string;
    };
    query?: {
        includeSubEvents?: 'true' | 'false';
        query?: string;
    };
};

export type ListEventsResponse = ({
    records: Array<EventRecord>;
});

export type ListEventsError = (unknown);

export type CreateEventData = {
    body?: CreateEventInput;
    path: {
        siteKey: string;
    };
};

export type CreateEventResponse = ((Event & {
    id: string;
    siteId: string;
    slug: string;
}));

export type CreateEventError = (unknown);

export type GetEventsPublicPreviewData = {
    path: {
        siteKey: string;
    };
    query?: {
        dir?: 'asc' | 'desc';
        featured?: (string | Array<(string)>);
        gt?: (number) | null;
        legacyId?: string;
        limit?: number;
        lt?: (number) | null;
        orderBy?: 'startDate' | 'createdAt' | 'updatedAt';
        page?: (number) | null;
        query?: (string) | null;
        rootOnly?: (string | Array<(string)>);
        tags?: (string | Array<(string)>);
        upcoming?: (string | Array<(string)>);
    };
};

export type GetEventsPublicPreviewResponse = ({
    records: Array<Event>;
    count: number;
});

export type GetEventsPublicPreviewError = (unknown);

export type GetEvent1Data = {
    path: {
        id: string;
        siteKey: string;
    };
};

export type GetEvent1Response = (EventRecord);

export type GetEvent1Error = (unknown);

export type UpdateEventData = {
    body?: UpdateEventInput;
    path: {
        id: string;
        siteKey: string;
    };
};

export type UpdateEventResponse = (EventRecord);

export type UpdateEventError = (unknown);

export type DeleteEventData = {
    path: {
        id: string;
        siteKey: string;
    };
};

export type DeleteEventResponse = (unknown);

export type DeleteEventError = (unknown);

export type GetEventProfilesData = {
    path: {
        eventId: string;
        siteKey: string;
    };
};

export type GetEventProfilesResponse = (EventProfiles);

export type GetEventProfilesError = (unknown);

export type AddProfileToEventData = {
    body?: AddProfileToEventInput;
    path: {
        eventId: string;
        siteKey: string;
    };
};

export type AddProfileToEventResponse = ((Event & {
    id: string;
    siteId: string;
    slug: string;
}));

export type AddProfileToEventError = (unknown);

export type RemoveProfileFromEventData = {
    path: {
        eventId: string;
        profileId: string;
        siteKey: string;
    };
};

export type RemoveProfileFromEventResponse = (unknown);

export type RemoveProfileFromEventError = (unknown);

export type GetEventRelationsData = {
    path: {
        id: string;
        siteKey: string;
    };
};

export type GetEventRelationsResponse = ((EventRelations & {
    hasParent?: boolean;
    hasChildren?: boolean;
    parents?: Array<unknown>;
    subEvents?: Array<unknown>;
}));

export type GetEventRelationsError = (unknown);

export type AddEventRelationData = {
    body?: EventRelationInput;
    path: {
        id: string;
        siteKey: string;
    };
};

export type AddEventRelationResponse = ((EventRelations & {
    hasParent?: boolean;
    hasChildren?: boolean;
    parents?: Array<unknown>;
    subEvents?: Array<unknown>;
}));

export type AddEventRelationError = (unknown);

export type RemoveEventRelationData = {
    body?: EventRelationInput;
    path: {
        id: string;
        siteKey: string;
    };
};

export type RemoveEventRelationResponse = ((EventRelations & {
    hasParent?: boolean;
    hasChildren?: boolean;
    parents?: Array<unknown>;
    subEvents?: Array<unknown>;
}));

export type RemoveEventRelationError = (unknown);

export type ListEventTagsData = {
    path: {
        id: string;
        siteKey: string;
    };
};

export type ListEventTagsResponse = (EventTagsResponse);

export type ListEventTagsError = (unknown);

export type UpdateEventTagsData = {
    body?: UpdateEventTagsInput;
    path: {
        id: string;
        siteKey: string;
    };
};

export type UpdateEventTagsResponse = (EventTagsResponse);

export type UpdateEventTagsError = (unknown);