// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from '@hey-api/client-next';
import type { GetSiteData, GetSiteResponse, GetEventsData, GetEventsResponse, GetEventData, GetEventResponse, GetPagesData, GetPagesResponse, GetPageData, GetPageResponse, GetProfilesData, GetProfilesResponse, GetProfileData, GetProfileResponse, GetProfileEventsData, GetProfileEventsResponse, GetProductsData, GetProductsResponse, GetProductData, GetProductResponse } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
};

export const getSite = <ThrowOnError extends boolean = false>(options: Options<GetSiteData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetSiteResponse, unknown, ThrowOnError>({
        url: '/api/v2/{siteKey}/public/site',
        ...options
    });
};

export const getEvents = <ThrowOnError extends boolean = false>(options: Options<GetEventsData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetEventsResponse, unknown, ThrowOnError>({
        url: '/api/v2/{siteKey}/public/events',
        ...options
    });
};

export const getEvent = <ThrowOnError extends boolean = false>(options: Options<GetEventData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetEventResponse, unknown, ThrowOnError>({
        url: '/api/v2/{siteKey}/public/events/{slug}',
        ...options
    });
};

export const getPages = <ThrowOnError extends boolean = false>(options: Options<GetPagesData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetPagesResponse, unknown, ThrowOnError>({
        url: '/api/v2/{siteKey}/public/pages',
        ...options
    });
};

export const getPage = <ThrowOnError extends boolean = false>(options: Options<GetPageData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetPageResponse, unknown, ThrowOnError>({
        url: '/api/v2/{siteKey}/public/pages/{slug}',
        ...options
    });
};

export const getProfiles = <ThrowOnError extends boolean = false>(options: Options<GetProfilesData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetProfilesResponse, unknown, ThrowOnError>({
        url: '/api/v2/{siteKey}/public/profiles',
        ...options
    });
};

export const getProfile = <ThrowOnError extends boolean = false>(options: Options<GetProfileData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetProfileResponse, unknown, ThrowOnError>({
        url: '/api/v2/{siteKey}/public/profiles/{slug}',
        ...options
    });
};

export const getProfileEvents = <ThrowOnError extends boolean = false>(options: Options<GetProfileEventsData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetProfileEventsResponse, unknown, ThrowOnError>({
        url: '/api/v2/{siteKey}/public/profiles/{slug}/events',
        ...options
    });
};

export const getProducts = <ThrowOnError extends boolean = false>(options: Options<GetProductsData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetProductsResponse, unknown, ThrowOnError>({
        url: '/api/v2/{siteKey}/public/products',
        ...options
    });
};

export const getProduct = <ThrowOnError extends boolean = false>(options: Options<GetProductData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetProductResponse, unknown, ThrowOnError>({
        url: '/api/v2/{siteKey}/public/products/{slug}',
        ...options
    });
};