// This file is auto-generated by @hey-api/openapi-ts

export const SiteSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            nullable: true
        },
        description: {
            type: 'string',
            nullable: true
        },
        defaultLocale: {
            type: 'string',
            nullable: true
        },
        timeZone: {
            type: 'string',
            nullable: true
        },
        image: {
            type: 'object',
            nullable: true,
            properties: {
                id: {
                    type: 'string'
                },
                siteId: {
                    type: 'string'
                },
                createdAt: {
                    type: 'string'
                },
                updatedAt: {
                    type: 'string'
                },
                uploaded: {
                    type: 'boolean'
                },
                inline: {
                    type: 'boolean'
                },
                url: {
                    type: 'string',
                    nullable: true
                },
                mimeType: {
                    type: 'string',
                    nullable: true
                },
                size: {
                    type: 'integer'
                },
                metadata: {
                    type: 'object',
                    nullable: true,
                    additionalProperties: {
                        nullable: true
                    }
                },
                title: {
                    type: 'string',
                    nullable: true
                },
                caption: {
                    type: 'string',
                    nullable: true
                },
                credit: {
                    type: 'string',
                    nullable: true
                },
                altText: {
                    type: 'string',
                    nullable: true
                }
            },
            required: ['id', 'siteId', 'createdAt', 'updatedAt', 'uploaded', 'inline', 'size', 'metadata']
        }
    }
} as const;

export const MediaItemSchema = {
    type: 'object',
    nullable: true,
    properties: {
        siteId: {
            type: 'string'
        },
        uploaded: {
            type: 'boolean'
        },
        inline: {
            type: 'boolean'
        },
        url: {
            type: 'string',
            nullable: true
        },
        mimeType: {
            type: 'string',
            nullable: true
        },
        size: {
            type: 'integer'
        },
        metadata: {
            type: 'object',
            nullable: true,
            additionalProperties: {
                nullable: true
            }
        },
        title: {
            type: 'string',
            nullable: true
        },
        caption: {
            type: 'string',
            nullable: true
        },
        credit: {
            type: 'string',
            nullable: true
        },
        altText: {
            type: 'string',
            nullable: true
        }
    },
    required: ['siteId', 'uploaded', 'inline', 'size', 'metadata']
} as const;

export const LocalizedContentSchema = {
    type: 'object',
    nullable: true,
    properties: {
        siteId: {
            type: 'string'
        },
        locale: {
            type: 'string'
        },
        title: {
            type: 'string',
            nullable: true
        },
        content: {
            type: 'string',
            nullable: true
        },
        shortContent: {
            type: 'string',
            nullable: true
        },
        extraContent: {
            type: 'string',
            nullable: true
        },
        excerpt: {
            type: 'string',
            nullable: true
        },
        metaTitle: {
            type: 'string',
            nullable: true
        },
        metaDescription: {
            type: 'string',
            nullable: true
        },
        keywords: {
            type: 'string',
            nullable: true
        },
        contentJSON: {
            type: 'object',
            nullable: true,
            additionalProperties: {
                nullable: true
            }
        }
    },
    required: ['siteId', 'locale', 'contentJSON']
} as const;

export const LocationSchema = {
    type: 'object',
    properties: {
        site: {
            '$ref': '#/components/schemas/Site'
        },
        image: {
            '$ref': '#/components/schemas/MediaItem'
        },
        localizedContent: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/LocalizedContent'
            }
        }
    },
    required: ['site', 'localizedContent']
} as const;

export const ProfileSchema = {
    type: 'object',
    properties: {
        slug: {
            type: 'string'
        },
        site: {
            '$ref': '#/components/schemas/Site'
        },
        image: {
            '$ref': '#/components/schemas/MediaItem'
        },
        localizedContent: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/LocalizedContent'
            }
        }
    },
    required: ['slug', 'site', 'localizedContent']
} as const;

export const TicketOnEventSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        price: {
            type: 'number'
        },
        externalLink: {
            type: 'string',
            nullable: true
        },
        currency: {
            type: 'string',
            nullable: true
        },
        roles: {
            type: 'array',
            items: {
                nullable: true
            }
        },
        localizedContent: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/LocalizedContent'
            }
        }
    },
    required: ['name', 'price', 'roles']
} as const;

export const EventSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        site: {
            '$ref': '#/components/schemas/Site'
        },
        description: {
            type: 'string',
            nullable: true
        },
        slug: {
            type: 'string'
        },
        image: {
            '$ref': '#/components/schemas/MediaItem'
        },
        startDate: {
            type: 'string'
        },
        endDate: {
            type: 'string',
            nullable: true
        },
        publishState: {
            type: 'string',
            enum: ['DRAFT', 'REQUEST', 'PUBLISHED', 'CANCELLED']
        },
        location: {
            '$ref': '#/components/schemas/Location'
        },
        artists: {
            type: 'array',
            items: {
                type: 'object',
                properties: {
                    profile: {
                        '$ref': '#/components/schemas/Profile'
                    }
                },
                required: ['profile']
            }
        },
        tickets: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/TicketOnEvent'
            }
        },
        localizedContent: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/LocalizedContent'
            }
        }
    },
    required: ['id', 'site', 'slug', 'startDate', 'endDate', 'publishState', 'artists', 'localizedContent']
} as const;

export const PageSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        order: {
            type: 'integer'
        },
        slug: {
            type: 'string'
        },
        featured: {
            type: 'boolean'
        },
        featuredExpiration: {
            type: 'string',
            nullable: true
        },
        date: {
            type: 'string',
            nullable: true
        },
        parentId: {
            type: 'string',
            nullable: true
        },
        site: {
            '$ref': '#/components/schemas/Site'
        },
        image: {
            '$ref': '#/components/schemas/MediaItem'
        },
        parent: {
            type: 'object',
            properties: {
                id: {
                    type: 'string'
                },
                siteId: {
                    type: 'string'
                },
                createdAt: {
                    type: 'string'
                },
                updatedAt: {
                    type: 'string'
                },
                recordType: {
                    type: 'string',
                    enum: ['SOURCE', 'PUBLISHED', 'REVISION']
                },
                revisionId: {
                    type: 'integer',
                    nullable: true
                },
                publishState: {
                    type: 'string',
                    enum: ['DRAFT', 'REQUEST', 'PUBLISHED', 'CANCELLED']
                },
                source: {
                    type: 'string',
                    nullable: true
                },
                publishedId: {
                    type: 'string',
                    nullable: true
                },
                dirty: {
                    type: 'boolean'
                },
                order: {
                    type: 'integer'
                },
                visible: {
                    type: 'boolean'
                },
                slug: {
                    type: 'string'
                },
                featured: {
                    type: 'boolean'
                },
                featuredExpiration: {
                    type: 'string',
                    nullable: true
                },
                date: {
                    type: 'string',
                    nullable: true
                },
                imageId: {
                    type: 'string',
                    nullable: true
                },
                userId: {
                    type: 'string',
                    nullable: true
                },
                parentId: {
                    type: 'string',
                    nullable: true
                }
            },
            required: ['id', 'siteId', 'createdAt', 'updatedAt', 'recordType', 'publishState', 'dirty', 'order', 'visible', 'slug', 'featured']
        },
        fullPath: {
            type: 'string',
            nullable: true
        },
        roles: {
            type: 'array',
            items: {
                type: 'object',
                properties: {
                    pageId: {
                        type: 'string'
                    },
                    accessRoleId: {
                        type: 'string'
                    },
                    accessRole: {
                        type: 'object',
                        properties: {
                            id: {
                                type: 'string'
                            },
                            siteId: {
                                type: 'string'
                            },
                            createdAt: {
                                type: 'string'
                            },
                            updatedAt: {
                                type: 'string'
                            },
                            name: {
                                type: 'string'
                            },
                            description: {
                                type: 'string',
                                nullable: true
                            }
                        },
                        required: ['id', 'siteId', 'createdAt', 'updatedAt', 'name']
                    }
                },
                required: ['pageId', 'accessRoleId', 'accessRole']
            }
        },
        localizedContent: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/LocalizedContent'
            }
        }
    },
    required: ['id', 'order', 'slug', 'featured', 'site', 'roles', 'localizedContent']
} as const;