// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-fetch';
import type { GetSiteData, GetSiteError, GetSiteResponse, GetEventsData, GetEventsError, GetEventsResponse, GetEventData, GetEventError, GetEventResponse, GetPagesData, GetPagesError, GetPagesResponse, GetPageData, GetPageError, GetPageResponse, GetProfilesData, GetProfilesError, GetProfilesResponse, GetProfileData, GetProfileError, GetProfileResponse } from './types.gen';

export const client = createClient(createConfig());

export const getSite = <ThrowOnError extends boolean = false>(options: Options<GetSiteData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetSiteResponse, GetSiteError, ThrowOnError>({
        ...options,
        url: '/api/v2/{siteKey}/public/site'
    });
};

export const getEvents = <ThrowOnError extends boolean = false>(options: Options<GetEventsData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetEventsResponse, GetEventsError, ThrowOnError>({
        ...options,
        url: '/api/v2/{siteKey}/public/events'
    });
};

export const getEvent = <ThrowOnError extends boolean = false>(options: Options<GetEventData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetEventResponse, GetEventError, ThrowOnError>({
        ...options,
        url: '/api/v2/{siteKey}/public/events/{slug}'
    });
};

export const getPages = <ThrowOnError extends boolean = false>(options: Options<GetPagesData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetPagesResponse, GetPagesError, ThrowOnError>({
        ...options,
        url: '/api/v2/{siteKey}/public/pages'
    });
};

export const getPage = <ThrowOnError extends boolean = false>(options: Options<GetPageData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetPageResponse, GetPageError, ThrowOnError>({
        ...options,
        url: '/api/v2/{siteKey}/public/pages/{slug}'
    });
};

export const getProfiles = <ThrowOnError extends boolean = false>(options: Options<GetProfilesData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetProfilesResponse, GetProfilesError, ThrowOnError>({
        ...options,
        url: '/api/v2/{siteKey}/public/profiles'
    });
};

export const getProfile = <ThrowOnError extends boolean = false>(options: Options<GetProfileData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetProfileResponse, GetProfileError, ThrowOnError>({
        ...options,
        url: '/api/v2/{siteKey}/public/profiles/{slug}'
    });
};